
:sectnums!:

[preface]
= Введение

== Об этом руководстве

Руководство пользователя HQbird содержит подробное описание функций и возможностей HQbird — расширенного дистрибутива Firebird, в том числе с примерами конфигурации и рекомендациями по передовому опыту.

== О IBSurgeon

Компания IBSurgeon (https://www.ib-aid.com) была основана в 2002 году с целью предоставить разработчикам и администраторам InterBase и Firebird услуги и инструменты, ориентированные на безопасность, производительность и доступность баз данных.
В России IBSurgeon в основном известен как iBase.ru, известный своими российским порталом по InterBase и Firebird  http://www.ibase.ru[www.ibase.ru].
IBSurgeon является членом Firebird Foundation и, как член технической рабочей группы, имеет прочные отношения с проектом Firebird, с прямыми представителями в Firebird-Admins и в комитете Firebird Foundation.
Сегодня IBSurgeon обслуживает тысячи компаний по всему миру, предлагая инструменты для экстренной помощи, оптимизации и обслуживания, а также различные услуги.
Нашими клиентами являются медицинские учреждения, финансовые организации и независимые поставщики программного обеспечения в Германии, Бразилии, России и других странах, а также все, у кого есть приложения на основе Firebird и/или InterBase.
Флагманским проектом IBSurgeon является HQbird, расширенный дистрибутив FirebirdSQL для больших баз данных с корпоративными функциями.

:sectnums: