[[hqbird-performance]]
= Performance enhancements

[[hqbird-performance-extconn-pool]]
== Pool of external connections

HQbird supports a pool of external connections for Firebird 2.5 and Firebird 3. The standard build of Firebird 4.0 and higher supports the creation of external connection pools out of the box.

An external connection pool allows execute `EXECUTE ON EXTERNAL` statements with less overhead in reconnecting to the external database.

[NOTE]
====
Please note -- this pool is allocated per Firebird instance.
====

The feature is managed in the `firebird.conf`:

[source,conf]
----
# ============================
# Settings of External Connections Pool
# ============================

# Set the maximum number of inactive (idle) external connections to retain at
# the pool. Valid values are between 0 and 1000.
# If set to zero, pool is disabled,
# i.e. external connection is destroyed immediately after the use.
#
# Type: integer
#
#ExtConnPoolSize = 0

# Set the time before destroying inactive external connection, seconds.
# Valid values are between 1 and 86400.
#
# Type: integer
#
#ExtConnPoolLifeTime = 7200
----

From the application point of view, no additional steps are required to use or do not use -- it is enabled or disabled in the server configuration, and absolutely seamless for the applications.

The following commands exist to manage pool:

* changes the pool size
+
[listing,subs=+quotes]
----
ALTER EXTERNAL CONNECTIONS POOL SET SIZE _N_
----
+
Example -- this command sets the size of a pool to 190 connections.
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL SET SIZE 190
----
* changes the lifetime of the pooled connection
+
[listing,subs=+quotes]
----
ALTER EXTERNAL CONNECTIONS POOL
SET LIFETIME _N_ {SECOND | MINUTE | HOUR}
----
+
Example -- this command limits the lifetime of a connection in the pool to 1 hour.
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL SET LIFETIME 1 HOUR
----
* clear all pooled connections
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL CLEAR ALL
----
* clear the oldest connection in the pool
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL CLEAR OLDEST
----

To get information about pool status, new context variables were introduced. The following example demonstrates their usage

[source,sql]
----
SELECT
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_SIZE') AS INT) AS POOL_SIZE,
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_IDLE_COUNT') AS INT) AS POOL_IDLE,
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_ACTIVE_COUNT') AS INT) AS POOL_ACTIVE,
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_LIFETIME') AS INT) AS POOL_LIFETIME
FROM RDB$DATABASE;
----

<<<

== Cached prepared statements

HQbird has the feature to improve the performance of Firebird (versions 4.0 and 5.0) engine in case of the many frequent and fast SQL queries: server-side cache of prepared SQL statements. Starting with Firebird 5.0, this feature is available in the standard out-of-the-box build.

=== Cached prepared statements in Firebird 3.0 and 4.0

This feature can be enabled in `firebird.conf` with the parameter `DSQLCacheSize`:

[source,conf]
----
# Size of DSQL statements cache.
# Maximum number of statements to cache.
# Use with care as it is per-attachment and could lead to big memory usage.
# Value of zero disables caching.
# Per-database configurable.
# Type: integer
#DSQLCacheSize = 0
----

The number specifies how many recent queries for each database connection to cache.

To apply the new value, Firebird restart is required.

By default, cache of prepared statements is 0, it means OFF. +
We recommend to carefully enable it: start with values like 4, 8, 16, to find the best performance effect.

[NOTE]
====
Please note: enabling cache of prepared statements increases the memory usage.
====

=== Cached prepared statements in Firebird 5.0

In Firebird 5.0, the prepared statement cache was redesigned and included in the `"vanilla"` build.

The cache of prepared statements is controlled by the `MaxStatementCacheSize` parameter in `firebird.conf`.

[source,conf]
----
# ----------------------------
# Maximum statement cache size
#
# The maximum amount of RAM used to cache unused DSQL compiled statements.
# If set to 0 (zero), statement cache is disabled.
#
# Per-database configurable.
#
# Type: integer
#
#MaxStatementCacheSize = 2M
----

By default, the prepared statement cache is enabled. To disable it, you need to set the `MaxStatementCacheSize` parameter to 0.

<<<

== TempSpaceLogThreshold: monitoring of big sorting queries and BLOBs

HQbird has a new parameter in `firebird.conf` in Firebird 2.5, Firebird 3.0, Firebird 4.0 and Firebird 5.0:

[source,conf]
----
TempSpaceLogThreshold = 1000000000 #bytes
----

When Firebird sees this parameter, it starts to log to `firebird.log` queries which produce large sortings: queries with `GROUP BY`, `ORDER BY`, etc.

When such query creates the sorting file which exceeds the specified threshold, the following message will appear in `firebird.log`:

----
SRV-DB1	Wed Nov 28 21:55:36 2018
	Temporary space of type "sort" has exceeded threshold of 1000000000 bytes.
	Total size: 10716980736, cached: 1455423488 bytes, on disk: 9263120384 bytes.
	Query: select count(*) from (select lpad('',1000,uuid_to_char(gen_uuid())) s
	       from rdb$types a,rdb$types b, rdb$types c  order by 1)
----

*Total size*:: the total size of sorting file

*Cached*:: the part of sorting which had fit into temporary space (specified by `TempCacheLimit` parameter)

*On disk*:: the part of sorting which was stored to the temporary file, which can be cached in the OS memory, or stored on disk (in the folder specified by `TempDirectories` parameter, or in the default temp folder)

For very big BLOBs the following message will appear in the `firebird.log`

----
SRV-DB1	Tue Nov 27 17:35:39 2018
	Temporary space of type "blob" has exceeded threshold of 500000000 bytes.
	Total size: 500377437, cached: 0 bytes, on disk: 501219328 bytes.
----

Use `TempSpaceLogThreshold` to find the non-optimized queries with big sorting and big BLOBs. Starting with Firebird 3.0 it will also report large hash tables (those caused by HASH JOINs).

If you encounter such queries, optimize them either with redesign of SQL query itself, or try to enable parameter `SortDataStorageThreshold`.

<<<

== SortDataStorageThreshold: REFETCH instead SORT for wide record sets

HQbird supports the new REFETCH optimization method. The standard build of Firebird version 4.0 and higher supports this optimization algorithm out of the box.

HQbird has a new parameter `SortDataStorageThreshold` in `firebird.conf` (Firebird 3.0+):

[source]
----
SortDataStorageThreshold=16384 # bytes
----

[NOTE]
====
Since version 4.0 this parameter has been renamed to `InlineSortThreshold`.

[source]
----
InlineSortThreshold=16384 # bytes
----
====

If the size of the record, returned by SQL query, will be more than specified threshold, Firebird will use the different approach for sorting record sets: REFETCH instead of SORT.

For example, we have the following query

[source,sql]
----
select tdetl.name_detl
    ,tmain.name_main
    ,tdetl.long_description
from tdetl
join tmain on tdetl.pid=tmain.id
order by tdetl.name_detl
----

with the following execution plan:

----
Select Expression
    -> Sort (record length: 32860, key length: 36)
        -> Nested Loop Join (inner)
            -> Table "TMAIN" Full Scan
            -> Filter
                -> Table "TDETL" Access By ID
                    -> Bitmap
                        -> Index "FK_TABLE1_1" Range Scan (full match)
----

In this case, the size of each record to be sorted is 32860+36 bytes. It can lead to the very big sort files, which will be written to the disk, and the overall query can slow.

With parameter `SortDataStorageThreshold=16384` or `InlineSortThreshold=16384`, Firebird will use plan REFETCH, where only key is sorted, and data are read from the database:

----
Select Expression
    -> Refetch
        -> Sort (record length: 76, key length: 36)
            -> Nested Loop Join (inner)
----

This approach can significantly (2-5 times) speed up queries with very wide sorted record sets (usually, heavy reports).

.Please note!
[NOTE]
====
It is not recommended to set `SortDataStorageThreshold` (`InlineSortThreshold`) less than 2048 bytes.
====

<<<

[[hqbird-performance-multi-threaded]]
== Multi-thread sweep, backup, restore

In HQbird, the possibility of multi-threaded execution of sweep, backup and restore has appeared, which speeds up their work from 2x to 6 times (depending on the specific database). Multi-threaded operations work in HQbird for Firebird 2.5, 3.0 and 4.0, in any architectures -- Classic, SuperClassic, SuperServer. For Firebird 5.0, multi-threaded operations are available in the "vanilla" version out of the box.

To enable multi-threaded execution, the `gfix` and `gbak` command-line utilities have the `–par _n_` option, where `n` is the number of threads that will be involved in a particular operation. In practice, choosing the number n should be correlated with the number of available processor cores.

For example

* `gfix –sweep database –par 8 ...`
* `gbak –b database backup –par 8 ...`
* `gbak –c backup database –par 8 ...`

Also, to control the number of threads and set their default number in `firebird.conf`, two new parameters are introduced that affect only sweep and restore, but not backup:

[source,conf]
----
# ============================
# Settings for parallel work
# ============================
#  Limit number of parallel workers for the single task. Per-process.
#  Valid values are from 1 (no parallelism) to 64. All other values
#  silently ignored and default value of 1 is used.
MaxParallelWorkers = 64
----

Example: if you set `MaxParallelWorkers = 10`, then you can

* run `gfix –sweep database –par 10`
* run `gfix –sweep database –par 5` and `gbak –c –par 5 ...`

That is, no more than 10 threads will be used in total. In case of exceeding (for example, if you set 6 threads for sweep and 6 threads for restore), for a process that exceeds the limit, the message "`No enough free worker attachments`" will be displayed).

Thus, to enable the multi-threaded capabilities of sweep and restore, you must set the `MaxParallelWorkers` parameter in `firebird.conf`

[source,conf]
----
MaxParallelWorkers = 64
----

and then restart Firebird.

The `ParallelWorkers` sets the number of threads used by sweep and restore by default if the `–par _n_` option is not specified.

[source,conf]
----
#  Default number of parallel workers for the single task. Per-process.
#  Valid values are from 1 (no parallelism) to MaxParallelWorkers (above).
#  Values less than 1 is silently ignored and default value of 1 is used.
#
ParallelWorkers = 1
----

For example, if `ParallelWorkers = 8`, then starting

----
gfix –sweep
----

without the `–par _n_` option will use 8 threads to execute sweep in parallel.

[IMPORTANT]
====
For restore, filling tables from backup is always performed in one thread, and only creating indexes is parallelized. Thus, the acceleration for restore depends on the number of indexes in the database and their size. Also, the `ParallelWorkers` parameter automatically affects the creation of indexes performed by the `CREATE INDEX` and `ALTER INDEX ... ACTIVE` operations.
====

As mentioned above, these options do not affect backup. +
The multi-threading of backup is regulated only by the `–par _n_` parameter in the command line:

* `gbak –b –par 6 ...`
* `gbak –b –par 8 –se ...`


[IMPORTANT]
====
If the database is in shutdown single state, when only 1 connection is allowed to the database, then in version 2.5 both sweep and backup with `–par _2_` or more will produce an error several seconds after starting:

* sweep -- connection lost to database
* backup -- ERROR: database ... shutdown (via xnet protocol, a line with this message will not be displayed in the backup log)

This is due to the fact that for these operations an appropriate number of database connections is required, more than 1.

In 3.0, only backup will throw an error "`ERROR: database ... shutdown`", sweep will work.

Multi-threaded restore, Firebird 2.5, 3.0 and 4.0, creates the database in shutdown multi mode, so such errors do not occur. However, there is a risk of connecting other applications from SYSDBA or the owner to the database in the restore process.
====

.Notes
* The new parameters in `firebird.conf` only affect sweep and restore, to simplify administration and eliminate ambiguity, it is recommended that you always explicitly specify the `–par n` parameter for `gfix` and `gbak` if you need to perform multi-threaded sweep, restore, and backup operations. For example, if you set `ParallelWorkers = 4` and do not specify `–par n`, then sweep and restore will use 4 threads by default, and backup will use 1 thread, because it does not use the values from `firebird.conf` neither locally nor with `–se`.

* The performance improvement does not necessarily depend on the number of processor cores and their compliance with the set value `–par n`. It depends on the number of cores, the Firebird architecture, and the disk subsystem performance (IOPS). Therefore, the optimal value `–par n` for your system must be selected experimentally.

<<<

[[hqbird-blob-append]]
== BLOB_APPEND function

Regular operator `||` (concatenation) with BLOB arguments creates temporary BLOB per every pair of args with BLOB. This could lead to the excessive memory consumption and growth of database file. The `BLOB_APPEND` function is designed to concatenate BLOBs without creating intermediate BLOBs.

In order to achieve this, the result BLOB is left open for writing instead of been closed immediately after it is filled with data. I.e. such blob could be appended as many times as required. Engine marks such blob with new internal flag `BLB_close_on_read` and closes it automatically when necessary.

*Available in*: DSQL, PSQL.

.Syntax:
[listing,subs=+quotes]
----
BLOB_APPEND(<blob> [, <value1>, ... <valueN]>
----

.Parameters of BLOB_APPEND function
[cols="1,2", options="header"]
|===
| Parameter
| Description

| blob
| BLOB or NULL.

| value
| Any type of value.
|===


*Return type*: BLOB, temporary, not closed (i.e. open for writing), marked by flag
`BLB_close_on_read`.

Input Arguments:

* The first argument is BLOB or NULL. The following options are possible:
** NULL:  creates new temporary blob, not closed, with flag `BLB_close_on_read`
** permanent BLOB (from table) or temporary already closed BLOB:
will create a new empty unclosed BLOB with the flag `BLB_close_on_read` and the contents of the first BLOB will be added to it
** temporary unclosed BLOB with the `BLB_close_on_read` flag: it will be used further
* other arguments can be of any type. The following behavior is defined for them:
** NULL ignored
** non-BLOBs are converted to string (as usual) and appended to the content of the result
** BLOBs, if necessary, are transliterated to the character set of the first argument and their contents are appended to the result

The `BLOB_APPEND` function returns a temporary unclosed BLOB with the` BLB_close_on_read` flag. This is either a new BLOB or the same as in the first argument. Thus, a series of operations like `blob = BLOB_APPEND (blob, ...)` will result in the creation of at most one BLOB (unless you try to add a BLOB to itself). This BLOB will be automatically closed by the engine when the client tries to read it, assign it to a table, or use it in other expressions that require reading the content.

[NOTE]
====
Testing a BLOB for NULL value using the `IS [NOT] NULL` operator does not read it, and therefore a temporary BLOB with the` BLB_close_on_read` flag will not be closed during such test.
====

[source,sql]
----
execute block
returns (b blob sub_type text)
as
begin
  -- will create a new temporary not closed BLOB
  -- and will write to it the string from the 2nd argument
  b = blob_append(null, 'Hello ');
  -- adds two strings to the temporary BLOB without closing it
  b = blob_append(b, 'World', '!');
  -- comparing a BLOB with a string will close it, because for this you need to read the BLOB
  if (b = 'Hello World!') then
  begin
  -- ...
  end
  -- will create a temporary closed BLOB by adding a string to it
  b = b || 'Close';
  suspend;
end
----


[TIP]
====
Use the `LIST` and` BLOB_APPEND` functions to concatenate BLOBs. This will save memory consumption, disk I/O, and prevent database growth due to the creation of many temporary BLOBs when using concatenation operators.
====


[example]
====
Let's say you need to build JSON on the server side. We have a PSQL package `JSON_UTILS` with a set of functions for converting primitive data types to JSON notation. Then the JSON building using the `BLOB_APPEND` function will look like this:

[source,sql]
----
EXECUTE BLOCK
RETURNS (
    JSON_STR BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
AS
  DECLARE JSON_M BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
BEGIN
  FOR
      SELECT
          HORSE.CODE_HORSE,
          HORSE.NAME,
          HORSE.BIRTHDAY
      FROM HORSE
      WHERE HORSE.CODE_DEPARTURE = 15
      FETCH FIRST 1000 ROW ONLY
      AS CURSOR C
  DO
  BEGIN
    SELECT
      LIST(
          '{' ||
          JSON_UTILS.NUMERIC_PAIR('age', MEASURE.AGE) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('height', MEASURE.HEIGHT_HORSE) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('length', MEASURE.LENGTH_HORSE) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('chestaround', MEASURE.CHESTAROUND) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('wristaround', MEASURE.WRISTAROUND) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('weight', MEASURE.WEIGHT_HORSE) ||
          '}'
      ) AS JSON_M
    FROM MEASURE
    WHERE MEASURE.CODE_HORSE = :C.CODE_HORSE
    INTO JSON_M;

    JSON_STR = BLOB_APPEND(
      JSON_STR,
      IIF(JSON_STR IS NULL, '[', ',' || ascii_char(13)),
      '{',
      JSON_UTILS.INTEGER_PAIR('code_horse', C.CODE_HORSE),
      ',',
      JSON_UTILS.STRING_PAIR('name', C.NAME),
      ',',
      JSON_UTILS.TIMESTAMP_PAIR('birthday', C.BIRTHDAY),
      ',',
      JSON_UTILS.STRING_VALUE('measures') || ':[', JSON_M, ']',
      '}'
    );
  END
  JSON_STR = BLOB_APPEND(JSON_STR, ']');
  SUSPEND;
END
----

A similar example using the usual concatenation operator `||` is an order of magnitude slower and does 1000 times more disk writes.
====

<<<

[[hqbird-performance-left-to-inner]]
== Transform LEFT joins into INNER

HQbird allow transform `LEFT` joins into `INNER` ones if the `WHERE` condition violates the outer join rules.

[NOTE]
====
Starting with Firebird 5.0, this functionality is available in the "`vanilla`" version of Firebird.
====

Example:

[source,sql]
----
SELECT *
FROM T1 LEFT JOIN T2 ON T1.ID = T2.ID
WHERE T2.FIELD1 = 0
----

In this case the condition `T2.FIELD1 = 0` effectively removes all the "fake NULL" rows of T2, so the result is the same as for the `INNER JOIN`. However, the optimizer is forced to use the T1->T2 join order while T2->T1 could also be considered. It makes sense to detect this case during join processing and internally replace `LEFT` with `INNER` before optimization starts.

This is primarily intended to improve "ad hoc" and machine-generated (e.g. ORM) queries.

[NOTE]
====
This optimization will not be enabled if a NULL value is checked, for example

[source,sql]
----
SELECT *
FROM T1 LEFT JOIN T2 ON T1.ID = T2.ID
WHERE T2.ID IS NULL
----

or

[source,sql]
----
SELECT *
FROM T1 LEFT JOIN T2 ON T1.ID = T2.ID
WHERE T2.ID IS NOT NULL
----
====

<<<

[[hqbird-performance-lwmonitoring]]
== Lightweight monitoring

Lightweight monitoring is based on a trace plugin that updates monitoring counters in real time. Counters are stored in shared memory, enabling efficient operation in Classic Server mode. Counter updates are unblocked, ensuring maximum efficiency. The shared memory size is fixed and defaults to 256 KB. This allows for the accumulation of information on 512 databases with 1-6 connections each, or on one database with 3580 connections. The fixed shared memory size also allows for (mostly) block-free operation of counters. You can change the shared memory size by setting a new value for the `MemorySize` parameter in the plugin configuration (see example below).

Currently, a small number of counters are supported. Monitoring collects information about two types of objects: the database (DB) and the connection. At the DB level, there is a separate set of counters for data on completed connections. This allows for continuous accumulation of information about a given DB.

=== Lightweight monitoring service

A new service has been created to receive monitoring information:

[source,cpp]
----
#define isc_action_svc_lwmonitoring	  32	// Lightweight monitoring
----

The service has two parameters. The first specifies the operation to be performed. Currently, this is the only operation, "`execute query`":

[source,cpp]
----
#define isc_spb_lwm_query			1
----

Four types of queries are implemented, as discussed below. To specify which query to execute, specify its number (1-4) as an integer parameter for `isc_spb_lwm_query`.

The second parameter is the database name, which is optional. It is specified using the well-known `isc_spb_dbname` tag. If this parameter is specified, the monitoring query is limited to the specified database; otherwise, information about all currently known databases is returned.

=== Lightweight Monitoring Queries

Let's describe four types of queries and what they return.

All queries return data as text, one row per element. An element can be database information, connection information, or aggregate information. The test is formatted as JSON to facilitate parsing and easy modification in future versions.

All queries in the first row return a string of the following format:

[source,json]
----
{"idQuery": 1, "tsQuery": "2024-04-17T00:17:58"}
----

where

* `idQuery` -- the query number (ID);
* `tsQuery` -- the timestamp of the query start time, using the server's local time and the common ISO-8601 format.

==== Query 1: Summary information about known databases and connections

Always returns one row of the form

[source,json]
----
{"cntDb": 1, "activeAtt": 1, "goneAtt": 0}
----

where

* `cntDb` -- number of databases;
* `activeAtt` -- number of active connections;
* `goneAtt` -- number of terminated connections.

==== Query 2: List of databases

Returns multiple rows of the form

[source,json]
----
{"dbName": "SECURITY2.FDB", "activeAtt": 1, "goneAtt": 2}
----

where

`dbName` is the database file name;
`activeAtt` is the number of active connections;
`goneAtt` is the number of terminated connections.

==== Query 3: Summary information about connections of each database

Returns multiple rows of the form

[source,json]
----
{"dbName": "SECURITY2.FDB", "activeAtt": 1, "goneAtt": 0, "doneTran": 1, "activeTran": 0, "prepReq": 0, "execReq": 0, "activeReq": 0}
----

where

`dbName` -- the database file name;
`activeAtt` -- the number of active connections;
`goneAtt` -- the number of completed connections;
`doneTran` -- the number of completed transactions;
`activeTran` -- the number of active transactions;
`prepReq` -- the number of prepared queries;
`execReq` -- the number of executed queries;
`activeReq` -- the number of active queries.

New counters:

`rowsFetched` -- the number of data rows retrieved by the application;
`execTime` -- query execution time;
`errors` -- the number of errors received by the application;
`fetches` -- the number of fetches;
`reads` -- the number of page reads;
`marks` -- the number of marks (executed before a page modification);
`writes` -- the number of page writes.

==== Query 4: Detailed information about each connection and each database

Returns multiple rows of the form

[source,json]
----
{"dbName": "SECURITY2.FDB", "activeAtt": 1, "goneAtt": 0} <1>

{"idAtt": 0, "pidAtt": 0, "doneTran": 0, "activeTran": 0, "prepReq": 0, "execReq": 0, "activeReq": 0} <2>

{"idAtt": 13925, "pidAtt": 11188, "doneTran": 1, "activeTran": 0, "prepReq": 0, "execReq": 0, "activeReq": 0} <2>
----

Where lines of type (1) describe the database, and lines of type (2) describe connections to that database. +
After each line about a database (1), there is at least one line of type (2) with connections to that specific database.

* `idAtt` -- connection_id, or 0 for summary information about completed connections;
* `pidAtt` -- ID of the server process handling this connection.

If an error occurs during request execution, either an exception is returned in the status vector or as service data in the following format:

[source,json]
----
{"errorMsg" : "Error text"}
----

For example

[source,json]
----
{"errorMsg" : "Unknown query: 5"}
----

=== Examples of calling the lightweight monitoring service

[source,bash]
----
fbsvcmgr service_mgr action_lwmonitoring lwm_query 1
----

[source,bash]
----
fbsvcmgr host:service_mgr action_lwmonitoring lwm_query 4 dbname employee
----

=== Configuring the lightweight monitoring service

A parameter with the name of the lightweight monitoring plugin has been added to `firebird.conf`

[source,conf]
----
MonitoringPlugin =
----

By default, the plugin is not configured and no monitoring is performed. The plugin name implemented for HQBird is `fblwmon`, so to use lightweight monitoring, you need to specify it in `firebird.conf`.

[source,conf]
----
MonitoringPlugin = fblwmon
----

The plugin itself is included in the HQBird build and is located in the `plugins` directory.

You can also set plugin parameters in its own configuration. Currently, one parameter is supported:

* `MemorySize` -- the plugin's total memory size in bytes.

The plugin configuration is set in the standard way (see `README.plugins.html`), for example, directly in `plugins.conf`:

[source,conf]
----
Plugin = fblwmon
{
	Config = lwmConfig
}

Config = lwmConfig
{
	# default 256KB
	MemorySize = 1M
}
----

=== Limit on the number of simultaneous connections

A built-in limit on the number of simultaneous connections is implemented using the lightweight monitoring service. The limit is based on the number of connections to a given database, but the limit value itself is the same for all databases (HQ 2.5 does not have a per-database setting). The limit values are set in `firebird.conf` using two integer parameters:

[source,conf]
----
WarnCountAttachments = 0
MaxCountAttachments = 0
----

The limit is checked at connection time and does not take into account the connection being created. The check uses the count of active connections to the given database:

* If `AttCount >= WarnCountAttachments and AttCount < MaxCountAttachments`, the connection is allowed, but a message similar to this is written to `firebird.log`:
+
----
Database XXX: number of attachments is above warning level (N >= W)
----

* If `AttCount >= MaxCountAttachments`, the connection is not allowed, and the client receives the message:
+
----
Statement failed, SQLSTATE = HY000
Number of attachments exceeds allowed maximum
----
+
and a message similar to this is written to `firebird.log`:
+
----
Database XXX: number of attachments is above maximum level (N >= M)
----

Connections to `security.db`, service connections, and connections with the `isc_dpb_no_db_triggers` tag in the DPB are not checked.

If `WarnCountAttachments = 0`, no warnings are issued.

If `MaxCountAttachments = 0`, connections are not blocked.

For this restriction to work, you must install and configure the lightweight monitoring plugin (see above).

== Settings for Working with Monitoring Tables

When executing a query involving any monitoring table, a so-called system snapshot is taken. This process interrupts all connections and flushes their counters and state to shared memory. Creating a system snapshot isn't free—the more connections and the more active they are, the longer it takes to query the monitoring tables. In Firebird 5.0, monitoring has become even more expensive with the introduction of the new `MON$COMPILED_STATEMENT` table, which essentially stores the contents of a cache of copied queries from all connections.

If the number of connections to the database exceeds 500, queries to the monitoring tables can take a considerable amount of time and place a significant load on the system. However, in most cases, the query is not executed against all monitoring tables, and the cost is the same as if the query were accessing all `MON$` tables. HQbird 2024R2 introduced additional configuration options that allow you to disable the populating of some `MON$` tables, simplifying monitoring queries.

* `FillMonCompiledStatements` -- whether to fill data for the `MON$COMPILED_STATEMENTS` table. The default value is `true`.
* `FillMonStatements` -- whether to fill data for the `MON$STATEMENTS` table. The default value is `true`.
* `FillMonCallStack` -- whether to fill data for the `MON$CALL_STACK` table. The default value is `true`.

These settings apply to each database individually, meaning you can set them in both `firebird.conf` and `databases.conf`. They are only available when using Firebird 5.0.

== `CREATE TABLE ... AS (SELECT ...)`

In HQbird 2024R2, when using Firebird 5.0.4, a new DDL statement `CREATE TABLE ... AS (SELECT ...)` is available.

Allows to create table with structure derived from `SELECT` query and, optionally, fill it with data of that query.

.Syntax
[listing,subs="+quotes,attributes"]
----
CREATE [GLOBAL TEMPORARY] TABLE <table_name>
    [(column_name [, ...])]
AS (<select>)
[WITH [NO] DATA]
[ON COMMIT PRESERVE | DELETE ROWS]
----

Columns for new table are derived from `<select>` query in the same way as for `CREATE VIEW` statement. Column names could be set explicitly using list of names. The number of item in names list and in `<select>` list should be the same. Only data type and `NOT NULL` attribute is inherited by new columns. Any kind of expression, calculated field, etc, in `<select>` list will be represented as a single persistent field. Identity attribute also ignored.

Optional `WITH [NO] DATA` clause specify if new table should be populated with data rows of `<select>` query. Default is `WITH NO DATA`. Data load happens at the very end stage of transaction commit, after all metadata-related work was done.

For `GLOBAL TEMPORARY TABLE ... ON COMMIT DELETE ROWS` data is not loaded despite of `WITH DATA` clause. `<select>` query is not executed if no data should be loaded.

.Creates copy of table employee and fill it with data
[example]
====
[source,sql]
----
CREATE TABLE emp2 AS (SELECT * FROM employee) WITH DATA;
----
====

== Materialized Views

*Materialized view* (MV) have properties of both persistent table and view. It is defined similar to a view and its source query is used by the engine to populate underlying MV table with data rows. It is not allowed to modify materialize view data using DML statements. The only way to update MV content is to run new `REFRESH` statement (see below). Like a regular table, MV can have indices of any kind. Unlike tables, it is not allowed to create constraints and triggers for MV.

=== Create, alter and drop MV

.Syntax
[listing,subs="+quotes,attributes"]
----
CREATE [OR ALTER] MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  [WITH [NO] DATA]

ALTER MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  [WITH [NO] DATA]
----

Creates new or modifies existing MV using specified query and optional list of column names. Optional `WITH DATA` clause specify that MV should be filled with data immediately after creation (altering). When `WITH NO DATA` specified, or when this clause is omitted, MV is not populated with data and remains empty. `ALTER` also drops all existing indices of MV. If regular (i.e. not materialized) view with the same name exists, error is raised.

[listing,subs="+quotes,attributes"]
----
RECREATE MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  [WITH [NO] DATA]
----

Drops *materialized* or *regular* view, if it exists, and creates a new *materialized* view.

There is no special command to delete MV, use regular `DROP VIEW` statement to do it.

=== Special commands

[listing,subs="+quotes,attributes"]
----
ALTER MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  TO NOT MATERIALIZED
----

Special kind of `ALTER` statement that converts *materialized* view into *regular* view with the same name. Dependent objects are not affected. All existing indices and data rows of former MV are dropped.

[listing,subs="+quotes,attributes"]
----
ALTER  VIEW <view_name> [(columns_names)]
  AS <query>
  TO MATERIALIZED
----

Special kind of `ALTER` statement that converts *regular* view into *materialized* view with the same name. Dependent objects are not affected.

=== Refreshing data of materialized views

To update the data of a materialized view, use the following statement.

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name> [CONCURRENTLY | DROP DATA] [CASCADE]
----

Executes MV query and replaces MV data with query ResultSet. All MV indexes are updated correspondingly. This is DDL command and actual execution is deferred until `COMMIT` of the current transaction. There are few forms of this command:

==== 1. Full reload in exclusive mode

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name>
----

deactivates all active indices, deletes all existing data, fill MV table with rows from MV query and activates all indices that was deactivated before. This is the fastest way of refresh, if there was many changes in tables of MV query. Note, this algorithm requires exclusive reservation of MV table to ensure no other connection attempts to query MV while it is refreshed. This is used also by `CREATE [OR ALTER]` and `RECREATE` statements for initial data load.

==== 2. Update only changed rows in shared mode

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name> CONCURRENTLY
----

This second form doesn't require exclusive reservation and allows concurrent connections to run statements referencing MV while it is refreshed. In this case, engine creates two ordered cursors for MV table data and for MV query ResultSet. Then merge algorithm is used to update changed rows, insert new rows and delete rows that not exists anymore. All changes of MV rows are made under transaction control therefore it provides safe and consistent concurrent access of the MV table. Both cursors are ordered basing on columns list of unique index.

*Unique index* must be built on the MV to allow this algorithm to work. Also, view query text stored in `RDB$VIEW_SOURCE` column should not be nullified as it is used by the engine to create internal merge statement.

This form of `REFRESH` statement should be preferred over first one when concurrent access is required or when there was not much changes in the tables of the MV query since previous refresh.

==== 3. Delete all data (exclusive mode)

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name> DROP DATA
----

This statement deletes data from MV table and indices. It is useful when DBA needs to free space occupied by MV data and indices. EX lock is required as in the first form of `REFRESH` statement.

==== 4. Cascading refresh

Use optional clause `CASCADE` to refresh all materialized views that given MV depends on. The refresh order ensures that each MV is handled after all MVs it depends on.

* Using `CONCURRENTLY` with `CASCADE` requires that all MVs to refresh must have unique index, else error will be raised.
* Using `DROP DATA` with `CASCADE` will delete data of all affected MVs.
* The statement put warning with name of each MV that will be handled into status-vector. It allows to know in advance (before commit) list and order of affected MVs.

=== gbak support

*gbak backup* requires no special support. Data of materialized view doesn't go into backup file - same as for regular views.

*gbak restore* refreshes all materialized views at the very end of restore process. MV's are refreshed in correct order, taking into account their dependencies on each other (see cascading refresh).

There is new command-line switch to make `gbak` not refresh MV's : `-NO_MATVIEWS`. It could be shortened up to 4 initial letters: `-NO_M`.

Corresponding option in Services API for `isc_action_svc_restore` action is `isc_spb_res_no_matviews`.

Note, backup with materialized view(s) can't be restored with Firebird version that doesn't supports MV's. To migrate onto such Firebird version, use `ALTER MATERIALIZED  VIEW ... TO NOT MATERIALIZED` statement before backup. This might be improved later.
