[[hqbird-eds-other-dbms]]
= Working with External Data Sources (Other DBMS)

In HQbird for Firebird 4.0 and above, the ability to work with external data sources has appeared, meaning not only with other Firebird databases but also with other DBMS. The following plugins are used for this:

* `MySQLEngine` for working with MySQL and MariaDB;
* `ODBCEngine` for working with any data source through a corresponding ODBC driver.

Currently, it is only available on Windows.

[[hqbird-eds-other-dbms-mysql]]
== MySQLEngine

The `MySQLEngine` plugin is designed for accessing MySQL and MariaDB databases.

For Firebird to recognize the plugin, you need to edit the `firebird.conf` configuration file, adding the `MySQLEngine` plugin to the provider list (`Providers` parameter):

[source,conf]
----
Providers = MySQLEngine,Remote,Engine13,Loopback
----

or

[source,conf]
----
Providers = Remote,Engine13,MySQLEngine,Loopback
----

The first option is preferable as it allows passing the username to EDS in the usual way.

=== Connection String Format

The connection string for the MySQLEngine plugin must start with the prefix `:mysql:` or `mysql://` followed by connection parameters in the form `<param>=<value>` separated by semicolons.

.Important
[IMPORTANT]
====
For the connection to work using the `mysql://` prefix, the `MySQLEngine` provider must be specified in the `Providers` parameter of the `firebird.conf` configuration file before the `Remote` provider.
====

Possible parameters:

* host -- the host or IP address where the MySQL server is located;
* port -- the port number the MySQL server listens on. Can be omitted if the default port (3306) is used;
* database -- the name of the database where queries will be executed;
* user -- the username;
* password -- the password.

Let's look at examples of executing queries against a MySQL database.

[source,sql]
----
execute block
returns (i integer)
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';

  for
    execute statement 'select 1'
    on external dsn_mysql
    as user 'root' password 'sa'
    into i
  do
    suspend;
end
----

In this case, the connection string uses the `mysql://` prefix, meaning the `MySQLEngine` provider must be specified before the `Remote` provider in the `Providers` configuration parameter.

Let's look at an example with a different connection prefix:

[source,sql]
----
execute block
returns (i integer)
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = ':mysql:host=localhost;port=3306;database=employees;user=root';

  for
    execute statement 'select 1'
    on external dsn_mysql
    as user null password 'sa'
    into i
  do
    suspend;
end
----

In this case, the connection string uses the `:mysql:` prefix, meaning the `MySQLEngine` provider must be specified after the `Remote` provider in the `Providers` configuration parameter.

Connecting using the `:mysql:` prefix has the following limitations:
* It is impossible to pass the username using the `USER` keyword; instead, specify `NULL` or an empty string in `USER`, and pass the username itself in the connection string as shown above.

.Remarks
[NOTE]
====
Do not specify the user password in the connection string (this is not secure); it's better to pass it using the `password` keyword.
====

Since using the `:mysql:` prefix makes working with the EDS subsystem unfamiliar, in all subsequent examples we will use the `mysql://` prefix.

=== Supported Query Types

The MySQLEngine plugin supports the following query types:

* `SELECT`
* `INSERT`, `UPDATE`, `DELETE`
* `CALL procedure(<params>)`

=== Query Output Parameters

Data types returned from a query

[cols="<2,<2",options="header",stripes="none"]
|===
^|MySQL Data Type
^|Firebird Data Type

| `TINYINT`
| `SMALLINT`

| `SMALLINT`
| `SMALLINT`

| `MEDIUMINT`
| `INTEGER`

| `INT`
| `INTEGER`

| `BIGINT`
| `BIGINT`

| `FLOAT`
| `FLOAT`

| `DOUBLE`
| `DOUBLE PRECISION`

| `DECIMAL`
| `VARCHAR(N)`

| `YEAR`
| `SMALLINT`

| `TIME`
| `TIME`

| `DATE`
| `DATE`

| `TIMESTAMP`
| `TIMESTAMP`

| `DATETIME`
| `TIMESTAMP`

| `CHAR(N)`, `BINARY(N)`
| `CHAR(N)`, `BINARY(N)`

| `VARCHAR(N)`, `VARBINARY(N)`
| `VARCHAR(N)`, `VARBINARY(N)`

| `TINYTEXT`, `TEXT`, `MEDIUMTEXT`, `LONGTEXT`
| `BLOB SUB_TYPE TEXT`

| `TINYBLOB`, `BLOB`, `MEDIUMBLOB`, `LONGBLOB`
| `BLOB SUB_TYPE BINARY`

| `JSON`
| `BLOB SUB_TYPE TEXT`

| `BIT(N)`
| `VARBINARY(N)`
|===

Example query with multiple fields:

[source,sql]
----
execute block
returns (
  emp_no bigint,
  birth_date date,
  first_name varchar(14),
  last_name varchar(16),
  gender char(1),
  hire_date date
)
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';

  for
    execute statement q'{
    select
      emp_no,
      birth_date,
      first_name,
      last_name,
      gender,
      hire_date
    from employees
    order by birth_date desc limit 5
    }'
    on external dsn_mysql
    as user 'root' password 'sa'
    into
      emp_no, birth_date, first_name, last_name, gender, hire_date
  do
    suspend;
end
----

A `SELECT` query always returns a cursor.

In MySQL, `CALL` queries can return values through `OUT` and `INOUT` parameters. Firebird's syntactic analyzer knows nothing about the `CALL` statement, so returning `OUT` and `INOUT` parameters is not supported.

[NOTE]
====
This may change in the future. Firebird 6.0 added the ability to call stored procedures using the `CALL` statement.
====

However, you can return `OUT` and `INOUT` parameters using local variables and sequential execution of multiple queries.

Suppose you have the following stored procedure:

[source,sql]
----
CREATE PROCEDURE `sp_test_add`(
  IN `A` INT,
  IN `B` INT,
  OUT `C` INT
)
LANGUAGE SQL
NOT DETERMINISTIC
NO SQL
SQL SECURITY DEFINER
BEGIN
  SET C = A + B;
END
----

Then the result of the procedure execution can be returned as follows:

[source,sql]
----
execute block
returns (
    c int
)
as
    declare dsn_mysql varchar(128);
    declare user_mysql varchar(25);
    declare psw_mysql varchar(25);
begin
    dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';
    user_mysql = 'root';
    psw_mysql = 'sa';

    execute statement 'SET @C=NULL'
    on external dsn_mysql
    as user user_mysql password psw_mysql;

    execute statement
    ('CALL sp_test_add(?, ?, @C)')
    (1, 2)
    on external dsn_mysql
    as user user_mysql password psw_mysql;

    execute statement
    'SELECT @C'
    on external dsn_mysql
    as user user_mysql password psw_mysql
    into c;

    suspend;
end
----

`CALL` queries can also return a cursor or multiple cursors. In the current version, returning a cursor from `CALL` queries is not supported. Working with multiple datasets using the `EXECUTE STATEMENT ... ON EXTERNAL` statement is not supported.

=== Query Input Parameters

The `MySQLEngine` plugin supports the use of parameters in queries. Parameters can be unnamed (positional) or named.

Example of using unnamed parameters:

[source,sql]
----
execute block
returns (
  emp_no bigint,
  birth_date date,
  first_name varchar(14),
  last_name varchar(16),
  gender char(1),
  hire_date date
)
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';

  for
    execute statement (q'{
    select
      emp_no,
      birth_date,
      first_name,
      last_name,
      gender,
      hire_date
    from employees
    where emp_no = ?
    }') (10020)
    on external dsn_mysql
    as user 'root' password 'sa'
    into
      emp_no, birth_date, first_name, last_name, gender, hire_date
  do
    suspend;
end
----

Example of using named parameters:

[source,sql]
----
execute block
returns (
  emp_no bigint,
  birth_date date,
  first_name varchar(14),
  last_name varchar(16),
  gender char(1),
  hire_date date
)
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';

  for
    execute statement (q'{
    select
      emp_no,
      birth_date,
      first_name,
      last_name,
      gender,
      hire_date
    from employees
    where emp_no = :emp_no
    }')
    (emp_no := 10020)
    on external dsn_mysql
    as user 'root' password 'sa'
    into
      emp_no, birth_date, first_name, last_name, gender, hire_date
  do
    suspend;
end
----

=== Limitation on Using Input Parameters

For named parameters to work, the EDS subsystem uses an internal preliminary query parser, which replaces all parameters of the form `:<name>` with `?` and saves the binding of the parameter name to its number. Therefore, this only works for queries whose syntax is similar to Firebird's syntax. For example, named parameters will not work for `CALL` queries. In this case, you must use unnamed parameters.

[source,sql]
----
set term ;#

execute block
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';

  execute statement
    ('CALL sp_conn_audit(:A_CONN_ID, :A_USER, :A_DT)')
    (A_CONN_ID := current_connection,
     A_USER := current_user,
     A_DT := localtimestamp)
  on external dsn_mysql
  as user 'root' password 'sa';
end#
----

[listing]
----
Statement failed, SQLSTATE = 42000
Execute statement error at isc_dsql_prepare :
335544382 : You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':A_CONN_ID, :A_USER, :A_DT)' at line 1
Statement : CALL sp_conn_audit(:A_CONN_ID, :A_USER, :A_DT)
Data source : Firebird:::mysql:host=localhost;port=3306;database=employees;user=root
-At block line: 7, col: 3
----

If you replace the named parameters with positional ones, the query will execute successfully.

[source,sql]
----
execute block
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = 'mysql://host=localhost;port=3306;database=employees';

  execute statement
    ('CALL sp_conn_audit(?, ?, ?)')
    (current_connection, current_user, localtimestamp)
  on external dsn_mysql
  as user 'root' password 'sa';
end#
----

[NOTE]
====
This may change in the future. Firebird 6.0 added the ability to call stored procedures using the `CALL` statement.
====

When Firebird executes `prepare`, it receives the types, sizes, and other properties of the query's input and output parameters. Then, based on this data, input and output messages are constructed, and buffers for data exchange are allocated. MySQL can return the types, sizes, and properties of output parameters (columns), but for input parameters, only their total number is returned. The MySQL C-API is designed so that the types, sizes, and other attributes for input parameters are set by the client application. However, in the Firebird API, it is impossible to completely define the input message on your own; it is only possible to transform the input message returned after `prepare` into another message (compatible in terms of types).

Since it's impossible to know the types of input parameters, we assign all parameters the type `VARCHAR(8191) CHARACTER SET UTF8`. Most Firebird types can be converted to a string and back. However, you cannot pass binary data (types `BINARY(N)`, `VARBINARY(N)` and `BLOB SUB_TYPE BINARY`) to such parameters, as they will be distorted. Furthermore, you cannot pass `BLOB SUB_TYPE TEXT` as parameters if the text exceeds 8191 characters in length.

[[hqbird-eds-other-dbms-odbc]]
== ODBCEngine

The `ODBCEngine` plugin is designed for accessing various databases through the ODBC interface.

For Firebird to recognize the plugin, you need to edit the `firebird.conf` configuration file, adding the `ODBCEngine` plugin to the provider list (`Providers` parameter):

[source,conf]
----
Providers = ODBCEngine,Remote,Engine13,Loopback
----

or

[source,conf]
----
Providers = Remote,Engine13,ODBCEngine,Loopback
----

The first option is preferable as it allows passing the username to EDS in the usual way.

=== Connection String Format

The connection string for the ODBCEngine plugin must start with the prefix `odbc://` or `:odbc:` followed by the connection parameters. There are two ways to connect to a database: using a DSN or using a full connection string for the specified driver.

[IMPORTANT]
====
For the connection to work using the `odbc://` prefix, the `ODBCEngine` provider must be specified in the `Providers` parameter of the `firebird.conf` configuration file before the `Remote` provider.
====

Possible connection string parameters:

* DSN -- the DSN of the data source (required if DRIVER is not present);
* DRIVER -- the name of the ODBC driver (required if DSN is not present);
* UID or USER -- the username;
* PWD or PASSWORD -- the password;
* other parameters specific to the chosen driver.

On Windows, if Firebird runs as a service, only *system* DSNs are visible.

Here are examples of connecting to a MySQL database. Suppose you have configured a system DSN named `test_dsn`, then the connection string would look like this:

[source,sql]
----
execute block
returns (
  i integer
)
as
begin
  for
    execute statement q'{
       select 1
    }'
    on external 'odbc://dsn=test_dsn'
    as user 'root' password '12345'
    into
      i
  do
    suspend;
end
----

In this case, the connection string uses the `odbc://` prefix, meaning the `ODBCEngine` provider must be specified before the `Remote` provider in the `Providers` configuration parameter.

Or using the `:odbc:` prefix:

[source,sql]
----
execute block
returns (
  i integer
)
as
begin
  for
    execute statement q'{
       select 1
    }'
    on external ':odbc:dsn=test_dsn;user=root'
    as user null password '12345'
    into
      i
  do
    suspend;
end
----

In this case, the connection string uses the `:odbc:` prefix, meaning the `ODBCEngine` provider must be specified after the `Remote` provider in the `Providers` configuration parameter.

Connecting using the `:odbc:` prefix has the following limitations:
* It is impossible to pass the username using the `USER` keyword; instead, specify `NULL` or an empty string in `USER`, and pass the username itself in the connection string as shown above.

[NOTE]
====
Do not specify the user password in the connection string (this is not secure); it's better to pass it using the `password` keyword.
====

Since using the `:odbc:` prefix makes working with the EDS subsystem unfamiliar, in all subsequent examples we will use the `odbc://` prefix.

==== DSN-less Connection String

Another option is to connect to the same database using a full connection string. The set of valid parameters in the connection string depends on the chosen driver.

For example, for the MariaDB driver, the connection would look like this:

[source,sql]
----
execute block returns (
  i integer
)
as
begin
  for
    execute statement 'select 1'
    on external 'odbc://DRIVER={MariaDB ODBC 3.1 Driver};SERVER=127.0.0.1;PORT=3306;DATABASE=test;CHARSET=utf8mb4'
    as user 'root' password '12345'
    into i
  do
    suspend;
end
----

[NOTE]
====
* Do not specify the user password in the connection string (this is not secure); it's better to pass it using the `password` keyword;
* Passing the username using the `USER` keyword in EDS will only work if you use the `odbc://` prefix; otherwise, pass the username in the connection string and specify `NULL` or an empty string in `USER`;
* For correct work with non-ASCII strings, always specify a connection character set compatible with UTF8 in the DSN. This is done differently in different ODBC drivers.
====

=== Data Type Mapping Between ODBC and Firebird

[cols="<2,<2",options="header",stripes="none"]
|===
|ODBC Data Type
|Firebird Data Type

|`SQL_CHAR`, `SQL_WCHAR`
|`VARCHAR(N)` if the length does not exceed 32765 bytes, otherwise `BLOB SUB_TYPE TEXT`

|`SQL_VARCHAR`, `SQL_WVARCHAR`
|`VARCHAR(N)` if the length does not exceed 32765 bytes, otherwise `BLOB SUB_TYPE TEXT`

|`SQL_BINARY`
|`VARBINARY(N)` if the length does not exceed 32765 bytes, otherwise `BLOB SUB_TYPE BINARY`

|`SQL_VARBINARY`
|`VARBINARY(N)` if the length does not exceed 32765 bytes, otherwise `BLOB SUB_TYPE BINARY`

|`SQL_TINYINT`, `SQL_SMALLINT`
|`SMALLINT`. If `SQL_SMALLINT` is unsigned, then `INTEGER`.

|`SQL_INTEGER`
|`INTEGER`. If `SQL_INTEGER` is unsigned, then `BIGINT`.

|`SQL_BIGINT`
|`BIGINT`. If `SQL_BIGINT` is unsigned, then `VARCHAR(20)`.

|`SQL_REAL`
|`FLOAT`

|`SQL_DOUBLE`, `SQL_FLOAT`
|`DOUBLE PRECISION`

|`SQL_TYPE_DATE`
|`DATE`

|`SQL_TYPE_TIME`
|`TIME`

|`SQL_TYPE_TIMESTAMP`
|`TIMESTAMP`

|`SQL_DECIMAL`
|`VARCHAR(N)`, where `N = precision + 2`

|`SQL_NUMERIC`
|`VARCHAR(N)`, where `N = precision + 2`

|`SQL_LONGVARCHAR`
|`BLOB SUB_TYPE TEXT`

|`SQL_WLONGVARCHAR`
|`BLOB SUB_TYPE TEXT`

|`SQL_LONGVARBINARY`
|`BLOB SUB_TYPE BINARY`

|`SQL_BIT`
|`BOOLEAN`

|`SQL_GUID`
|`VARBINARY(16)`
|===

=== Query Types

A `SELECT` query always returns a cursor.

`CALL` queries can return values through `OUT` and `INOUT` parameters. Firebird's syntactic analyzer knows nothing about the `CALL` statement, so returning `OUT` and `INOUT` parameters is not supported.

[NOTE]
====
This may change in the future. Firebird 6.0 added the ability to call stored procedures using the `CALL` statement.
====

`CALL` queries can also return a cursor or multiple cursors. In the current version, returning a cursor from `CALL` queries is not supported. Working with multiple datasets using the `EXECUTE STATEMENT ... ON EXTERNAL` statement is not supported.

Queries of type `INSERT`, `UPDATE`, `DELETE` usually do not return data unless a `RETURNING` clause is specified; otherwise, a cursor is returned.

Example of executing a `SELECT` query.

[source,sql]
----
execute block
returns (
  id     integer,
  title  varchar(255),
  body blob sub_type text,
  bydate varchar(50)
)
as
declare sql varchar(8191);
begin
  sql = Q'{
SELECT
  id,
  title,
  body,
  bydate
FROM article
}';
  for
    execute statement (:sql)
    on external 'odbc://DRIVER={MariaDB ODBC 3.1 Driver};SERVER=127.0.0.1;PORT=3306;DATABASE=articles;CHARSET=utf8mb4'
    as user 'root' password 'root'
    into
      id,
      title,
      body,
      bydate
  do
    suspend;
end
----

=== Query Input Parameters

The `ODBCEngine` plugin supports the use of parameters in queries. Parameters can be unnamed (positional) or named.

Example of using unnamed parameters:

[source,sql]
----
execute block
returns(
   CODE_SEX INTEGER,
   NAME VARCHAR(70),
   NAME_EN VARCHAR(70)
)
as
declare xSQL varchar(8191);
declare xCODE_SEX INT = 1;
begin
  xSQL = '
SELECT
  CODE_SEX,
  NAME,
  NAME_EN
FROM sex
WHERE CODE_SEX = ?
';
  for
    execute statement (:xSQL)
    (xCODE_SEX)
    on external 'odbc://DRIVER={MariaDB ODBC 3.1 Driver};SERVER=127.0.0.1;PORT=3306;DATABASE=test;CHARSET=utf8mb4'
    as user 'test' password '12345'
    into CODE_SEX, NAME, NAME_EN
  do
    suspend;
end
----

Example of using named parameters:

[source,sql]
----
execute block
returns(
   CODE_SEX INTEGER,
   NAME VARCHAR(70),
   NAME_EN VARCHAR(70)
)
as
declare xSQL varchar(8191);
declare xCODE_SEX INT = 1;
begin
  xSQL = '
SELECT
  CODE_SEX,
  NAME,
  NAME_EN
FROM sex
WHERE CODE_SEX = :A_CODE_SEX
';
  for
    execute statement (:xSQL)
    (A_CODE_SEX := xCODE_SEX)
    on external 'odbc://DRIVER={MariaDB ODBC 3.1 Driver};SERVER=127.0.0.1;PORT=3306;DATABASE=test;CHARSET=utf8mb4'
    as user 'test' password '12345'
    into CODE_SEX, NAME, NAME_EN
  do
    suspend;
end
----

=== Limitation on Using Input Parameters

For named parameters to work, the EDS subsystem uses an internal preliminary query analysis, which replaces all parameters of the form `:<name>` with `?` and saves the binding of the parameter name to its number. Therefore, this only works for queries whose syntax is similar to Firebird's syntax. For example, named parameters will not work for `CALL` queries. In this case, you must use unnamed parameters.

When Firebird executes `prepare`, it receives the types, sizes, and other properties of the query's input and output parameters. Then, based on this data, input and output messages are constructed, and buffers for data exchange are allocated.

Not all ODBC drivers support describing input parameters with the `SQLDescribeParam` function. Some ODBC drivers formally support this function, but in reality, the description does not correspond to reality. For example, the ODBC driver for MySQL returns the type `SQL_VARCHAR` with a length of 255 characters for all input parameters.
