[[hqbird-fbstreaming]]
= Firebird Streaming

Firebird streaming is a technology for asynchronously publishing events that occur during the analysis of the replication log.

The service (daemon) `fb_streaming` is used for event processing. The service monitors for new replication log files, analyzes them and generates events that are processed by one of the plugins.

Available plugins:

* `kafka_cdc_plugin` -- publishing CDC (Change Data Capture) events in Kafka;
* `rabbitmq_plugin` -- publishing replication events in RabbitMQ;
* `mongodb_events_plugin` -- saving replication events in MongoDB;
* `fts_lucene_plugin` -- automatic updating of full-text indexes without triggers (IBSurgeon Full Text Search UDR);
* `simple_json_plugin` -- saving replication logs in JSON format.

Firebird Streaming technology is designed to work with replication logs in Firebird 4.0 format and higher. It will not work with Firebird 2.5 and 3.0 replication segments.

The `fb_streaming` service and its plugins are not included in the HQBird 2024 distribution. They can be provided to our clients upon separate request.

== How fb_streaming works?

The `fb_streaming` service (daemon) checks the contents of the directory specified for the task in the `fb_streaming.conf` configuration file, and if this directory contains unprocessed replication log files, then it analyzes them and generates appropriate events that are processed by the specified plugin . The last replication segment number processed is written to a control file named `<database guid>`. The location of this file can be specified in the `lockDir` configuration parameter. If this parameter is not specified, then by default the control file `<database guid>` will be created in the directory specified as the archive log directory for the task.

[IMPORTANT]
====
Replication log files must be in an archived state.
====

The control file is necessary to restore operation after a sudden shutdown of the service (for example, the lights were turned off or the server was rebooted). It contains the following information:

- control information (database GUID, size, etc.);
- number of the last processed segment and position in it;
- the number of the segment with the oldest active transaction (a transaction can start in one segment and end in another);
- a list of all active transactions in the form of pairs `{tnxNumber, segmentNumber}`, where `segmentNumber` is the number of the segment in which the transaction began.

If an emergency situation occurs and the `fb_streaming` service has been stopped, then the next time it starts, it reads the control file and rereads all replication segments, starting with the number of the segment with the oldest active transaction, and ending with the number of the last processed segment. In the process of reading these segments, `fb_streaming` repeats all events from the list of active transactions, after which it goes into normal operation.

A replication segment file is deleted if its number is less than the segment number with the oldest active transaction.

During the analysis of replication logs, the following events may occur:

- transaction start (START);
- preparation of a two-phase transaction (PREPARE);
- transaction commit (COMMIT);
- transaction rollback (ROLLBACK);
- set savepoint (SAVE);
- rollback to savepoint (UNDO);
- release savepoint (RELEASE);
- set value of the generator (SET SEQUENCE);
- execution of the SQL statement (EXECUTE SQL). Such events occur only for DDL statements;
- save BLOB (BLOB);
- inserting a new record into the table (INSERT);
- updating records in the table (UPDATE);
- deleting a record from a table (DELETE).

Which of them will be processed and which are simply ignored depends on the selected plugin.

== Installing and starting a service on Windows

Go to the `fb_streaming` installation directory.

Perform the settings in the `fb_streaming.conf` configuration file.

After setting up the configuration file, you can install and start the service.

For help using and installing the service, type the command

[source,bash]
----
fb_streaming help
----

You will be shown information on installing, removing, starting and stopping the service:

[listing]
----
================================================================================
 Firebird streaming service

 Copyright (c) 2023 IBSurgeon ltd.
================================================================================

usage: fb_streaming <command> [service_name]
Possible commands are:
    install            install service
    remove             remove service
    start              start service
    stop               stop service
----

After setting up the configuration file, you can install and start the service by running the following commands:

[listing]
----
c:\streaming>fb_streaming install
Success install service!

c:\streaming>fb_streaming start
Service start pending...
Service started successfully.
----

Once installed, you can manage the service through the graphical utility - services (`services.msc`).

To remove a service, run the following commands:

[listing]
----
c:\streaming>fb_streaming stop
Service is already stopped.

c:\streaming>fb_streaming remove
Service deleted successfully
----

[NOTE]
====
If you have multiple `fb_streaming` services running, they must be given unique names when installed, started, stopped, and removed.
====

== Installing and starting a service on Linux

Go to the `fb_streaming` installation directory. On Linux this is usually the `/opt/fb_streaming` directory.

Perform the settings in the `fb_streaming.conf` configuration file.

After setting up the configuration file, you can install and start the service by running the following commands:

[source,bash]
----
sudo systemctl enable fb_streaming

sudo systemctl start fb_streaming
----

To remove a service, run the following commands:

[source,bash]
----
sudo systemctl stop fb_streaming

sudo systemctl disable fb_streaming
----

== Configuring the service (daemon) fb_streaming

To configure the service, use the `fb_streaming.conf` file, which should be located in the `fb_streaming` root directory.

The configuration file syntax is exactly the same as for Firebird configuration files.

The `#` character denotes a comment, that is, everything that follows this character to the end of the line is ignored.

The structure of the `fb_streaming.conf` configuration file looks like this:

[listing]
----
# logLevel = info

# pluginDir = $(root)/stream_plugins

task = <sourceDir_1>
{
# other parameters of task 1
}

task = <sourceDir_2>
{
# other parameters of task 2
}
----

General parameters of the `fb_streaming` service (daemon):

- `logLevel` -- logging level (default info). Allowed logging levels: trace, debug, info, warning, error, critical, off.
- `pluginDir` -- directory where `fb_streaming` plugins are located. Defaults to `$(root)/stream_plugins`. The macro substitution `$(root)` denotes the root directory of the service (daemon).

Next are the task configurations. One service instance can serve several tasks at once. Each task runs in its own thread.
A separate task is created for each directory with replication log files.

Here `sourceDir_N` is the directory with replication log files. These directories must be unique. The same directory cannot be processed by more than one task.

The main parameters of the task:

- `controlFileDir` -- the directory in which the control file will be created (by default, the same directory as `sourceDir`);
- `errorTimeout` -- timeout after error in seconds. After this timeout expires, the segments will be re-scanned and the task will be restarted. The default is 60 seconds;
- `database` -- database connection string (required);
- `username` -- user name for connecting to the database;
- `password` -- password for connecting to the database;
- `plugin` -- plugin that processes events that occur during the analysis of the replication log (required);
- `deleteProcessedFile` -- whether to delete the log file after processing (`true` by default).

The task may also contain other parameters specific to the plugin being used.

Plugins for handling events from the replication log are located in dynamic libraries. The name of the dynamic library file depends on the operating system and is built as follows:

- for Windows `<plugin name>.dll`
- for Linux `lib<plugin name>.so`

The dynamic library file must be located in the `stream_plugins` directory, or in the one specified in the `pluginDir` parameter.

== Firebird configuration tricks

Please note: replication log archives folder should only be processed by a single `fb_streaming` service task. If you want to have logical replication running at the same time, or multiple services running on the log archive, then duplication of archive logs in different directories is necessary.

This can be done in the `replication.conf` file as follows

[listing]
----
...
journal_archive_directory = <archiveDir>
journal_archive_command = "copy $(pathname) $(archivepathname) && copy $(pathname) <archiveDirTask>
...
----

Here `archiveDir` is the directory of archives for asynchronous replication, `archiveDirTask` is the directory of archives for the service task `fb_streaming`.

include::fbstreaming/_hqbird-fbstreaming-kafka-cdc-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-rabbitmq-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-mongodb-events-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-fts-lucene-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-simple-json-plugin.adoc[leveloffset=2]
