[[hqbird-ocr-udr]]
= OCR-UDR -- function to recognizing text from images

HQbird includes OCR-UDR which contains function to recognizing text from images.

UDR OCR is based on the free text recognition library Tesseract OCR 4.1, released under the Apache License, Version 2.0.

To register OCR-UDR, you need to execute the following script:

[source,sql]
----
CREATE OR ALTER FUNCTION GET_OCR_TEXT (
    PIX_DATA BLOB SUB_TYPE BINARY,
    PPI      SMALLINT = NULL)
RETURNS BLOB SUB_TYPE TEXT
EXTERNAL NAME 'ocrudr!getOcrText!eng' ENGINE UDR;

COMMENT ON FUNCTION GET_OCR_TEXT IS
'Recognizing text from images';

COMMENT ON PARAMETER GET_OCR_TEXT.PIX_DATA IS
'Image';

COMMENT ON PARAMETER GET_OCR_TEXT.PPI IS
'Pix Per Inch. Some image formats do not store this information. For scanned
pages are usually 200-300 ppi. The minimum value is 70.';
----

[IMPORTANT]
====
Pay attention to the `EXTERNAL NAME` in it after the module name and entry point with "!" the name of the dictionary is indicated.

Where is `eng` a dictionary from `tessdata` catalog, which is used for recognition.
Several dictionaries can be listed here, for example `rus+eng`. If absent, then the dictionary `eng` is used.

The set contains a limited number of dictionaries.
A complete list of dictionaries is available at: https://github.com/tesseract-ocr/tessdata_best[] (high recognition quality)
or https://github.com/tesseract-ocr/tessdata_fast[] (high recognition speed).
====

The library supports text recognition from images in PNG, JPEG, GIF formats.

== Example of using OCR-UDR

Suppose you have a `DOCS` table that stores scans of documents, defined as follows:

[source,sql]
----
CREATE TABLE DOCS (
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME       VARCHAR(127) NOT NULL,
    PIC        BLOB SUB_TYPE 0,
    TXT        BLOB SUB_TYPE TEXT,
    PROCESSED  BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT PK_DOCS PRIMARY KEY (ID)
);
----

Images for recognition are saved in the `PIC` field, the recognized text in the `TXT` field.

To recognize text from a single image, you can use the query:

[source,sql]
----
SELECT GET_OCR_TEXT(pic, 200) as txt
FROM docs
WHERE docs.id = 2;
----

The next query recognizes text from images and saves it to the `TXT` field.

[source,sql]
----
UPDATE DOCS
SET TXT = GET_OCR_TEXT(PIC, 200),
    PROCESSED = TRUE
WHERE PROCESSED IS FALSE;
----
