[[hqbird-fbstreaming]]
= Firebird Streaming

Firebird streaming -- это технология асинхронной публикации событий возникающих в процессе анализа журнала репликации.

Для обработки событий используется служба (демон) `fb_streaming`. Служба отслеживает новые файлы журнала репликации, анализирует их, и генерирует события, которые обрабатываются одним из плагинов.

Доступные плагины:

* `kafka_cdc_plugin` -- публикация CDC (Change Data Capture) событий в Kafka;
* `rabbitmq_plugin` -- публикация событий репликации в RabbitMQ;
* `mongodb_events_plugin` -- сохранение событий репликации в MongoDB;
* `fts_lucene_plugin` -- автоматическое обновление полнотекстовых индексов без триггеров (IBSurgeon Full Text Search UDR);
* `simple_json_plugin` -- сохранение журналов репликации в формате JSON.

Технология Firebird Streaming разработана для работы с журналами репликации с форматом Firebird 4.0 и выше. С сегментами репликации Firebird 2.5 и 3.0 она работать не будет.

Служба `fb_streaming` и её плагины не входит в штатный дистрибутив HQBird 2024. Они могут быть предоставлена нашим клиентам по отдельному запросу.

== Принцип работы fb_streaming

Служба (демон) `fb_streaming` проверяет содержимое директории, указанной для задачи в конфигурационном файле `fb_streaming.conf`, и если в этой директории присутствует ещё не обработанные файлы журнала репликации, то она анализирует их, и генерирует соответствующие события, которые обрабатываются указанным плагином. Последний номер обработанного сегмента репликации записывается в контрольный файл с именем `<database guid>`. Расположение этого файла можно указать в параметре конфигурации `lockDir`. Если этот параметр не указан, то по умолчанию контрольный файл `<database guid>` будет создан в директории, указанной в качестве директории для журналов архивов для задачи.

[IMPORTANT]
====
Файлы журналов репликации должны быть в архивном состоянии.
====

Контрольный файл необходим для восстановления работы после внезапного завершения работы службы (например выключили свет или перезагрузили сервер). Он содержит следующую информацию:

- контрольную информацию (GUID базы данных, размер и т.д.);
- номер последнего обработанного сегмента и позицию в нём;
- номер сегмента с самой старой активной транзакцией (транзакция может начаться в одном сегменте, а завершиться в другом);
- список всех активных транзакций в виде пар `{tnxNumber, segmentNumber}`, где `segmentNumber` номер сегмента в котором транзакция началась.

Если произошла внештатная ситуация и служба `fb_streaming`  была остановлена, то при следующем старте она читает контрольный файл, и перечитывает все сегменты репликации, начиная с номера сегмента с самой старой активной транзакцией, и заканчивая номером последнего обработанного сегмента. В процессе чтения этих сегментов `fb_streaming`  повторяет все события из списка активных транзакций, после чего переходит в штатный режим работы.

Файл сегмента репликации удаляется, если его номер меньше чем номер сегмента с самой старой активной транзакцией.

В процессе анализа журналов репликации могут возникать следующие события:

- старт транзакции (START);
- выполнение первой фазы подтверждения двухфазной транзакции (PREPARE);
- подтверждение транзакции (COMMIT);
- откат транзакции (ROLLBACK);
- установка точки сохранения (SAVE);
- откат точки сохранения (UNDO);
- освобождение точки сохранения (RELEASE);
- установка значения генератора (SET SEQUENCE);
- выполнение SQL оператора (EXECUTE SQL). Такие события происходят только для DDL операторов;
- сохранение BLOB (BLOB);
- вставка новой записи в таблицу (INSERT);
- обновление записи в таблице (UPDATE);
- удаление записи из таблицы (DELETE).

Какие из них будут обработаны, а какие просто проигнорированы зависит от выбранного плагина.

== Установка и запуск службы в Windows

Перейдите в каталог установки `fb_streaming`.

Выполните настойку в файле конфигурации `fb_streaming.conf`.

После настройки файла конфигурации, вы можете установить и запустить службу.

Для получения справки по использованию и установке службы наберите

[source,bash]
----
fb_streaming help
----

Вам будет выведена информация по установке, удаления, старту и остановки службы:

[listing]
----
================================================================================
 Firebird streaming service

 Copyright (c) 2023 IBSurgeon ltd.
================================================================================

usage: fb_streaming <command> [service_name]
Possible commands are:
    install            install service
    remove             remove service
    start              start service
    stop               stop service
----

После настройки файла конфигурации, вы можете установить и запустить службу, выполнив следующие команды:

[listing]
----
c:\streaming>fb_streaming install
Success install service!

c:\streaming>fb_streaming start
Service start pending...
Service started successfully.
----

После установки вы можете управлять службой через графическую утилиту - службы (`services.msc`).

Для удаления службы выполните следующие команды:

[listing]
----
c:\streaming>fb_streaming stop
Service is already stopped.

c:\streaming>fb_streaming remove
Service deleted successfully
----

[NOTE]
====
Если у вас будут функционировать несколько служб `fb_streaming`, то при установке, запуске, остановке и удалении им надо дать уникальные имена.
====

== Установка и запуск демона в Linux

Перейдите в каталог установки `fb_streaming`. В Linux это обычно директория `/opt/fb_streaming`.

Выполните настойку в файле конфигурации `fb_streaming.conf`.

После настройки файла конфигурации, вы можете установить и запустить службу, выполнив следующие команды:

[source,bash]
----
sudo systemctl enable fb_streaming

sudo systemctl start fb_streaming
----

Для удаления службы выполните следующие команды:

[source,bash]
----
sudo systemctl stop fb_streaming

sudo systemctl disable fb_streaming
----

== Настройка конфигурации служба (демон) fb_streaming

Для конфигурации службы используется файл `fb_streaming.conf`, который должен быть расположен в корневой директории `fb_streaming`.

Синтаксис файла конфигурации точно такой же как для файлов конфигурации Firebird.

Символ `#` обозначает комментарий, то есть всё что следует за этим символом до конца строки игнорируется.

Структура файла конфигурации `fb_streaming.conf` выглядит так:

[listing]
----
# logLevel = info

# pluginDir = $(root)/stream_plugins 

task = <sourceDir_1>
{
# другие параметры задачи 1
}

task = <sourceDir_2>
{
# другие параметры задачи 2
}
----

Общие параметры службы (демона) `fb_streaming`:

- `logLevel` -- уровень журналирования (по умолчанию info). Допускаются уровни журналирования: trace, debug, info, warning, error, critical, off.
- `pluginDir` -- директория, где размещаются плагины `fb_streaming`. По умолчанию `$(root)/stream_plugins`. Макроподстановка `$(root)` обозначает корневую директорию службы (демона).

Далее следуют конфигурации задач. Один экземпляр службы может обслуживать сразу несколько задач. Каждая задача работает в своём потоке. 
На каждый каталог с файлами журнала репликации создаётся своя задача.

Здесь `sourceDir_N` -- директория с файлами журнала репликации. Эти директории должны быть уникальны. Одну и ту же директорию нельзя обрабатывать более чем одной задачей.

Основные параметры задачи:

- `controlFileDir` -- директория в которой будет создан контрольный файл (по умолчанию та же директория, что и `sourceDir`);
- `errorTimeout` -- тайм-аут после ошибки, в секундах. По истечению этого таймаута будет произведено повторное сканирование сегментов и перезапуск задачи. По умолчанию равен 60 секунд;
- `database` -- строка подключения к базе данных (обязательный);
- `username` -- имя пользователя для подключения к базе данных;
- `password` -- пароль для подключения к базе данных;
- `plugin` -- плагин, который обрабатывает события, возникающие в процессе анализа журнала репликации (обязательный);
- `deleteProcessedFile` -- удалять ли файл журнала после обработки (по умолчанию `true`). 

Задача может содержать также другие параметры, специфичные для используемого плагина.

Плагины для обработки событий из журнала репликации расположены в динамических библиотеках.
Имя файла динамической библиотеки зависит от операционной системы и строится следующим образом:

- для Windows `<имя плагина>.dll`
- для Linux `lib<имя плагина>.so`

Файл динамической библиотеки должен быть расположен в директории `stream_plugins`, или в той, что указана в параметре `pluginDir`.

== Трюки при конфигурации Firebird

Обратите внимание: папка с архивами журналов репликации должна обрабатываться только одной задачей службы `fb_streaming`. Если вы хотите чтобы, одновременно работала логическая репликация или с архивом журналов работало несколько служб, то необходимо дублирование архивных журналов в разные директории.

Это можно сделать в файле `replication.conf` следующим образом

[listing]
----
...
journal_archive_directory = <archiveDir>
journal_archive_command = "copy $(pathname) $(archivepathname) && copy $(pathname) <archiveDirTask>
...
----

Здесь `archiveDir` -- директория архивов для работы асинхронной репликации, `archiveDirTask` -- директория архивов для работы задачи службы `fb_streaming`.

include::fbstreaming/_hqbird-fbstreaming-kafka-cdc-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-rabbitmq-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-mongodb-events-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-fts-lucene-plugin.adoc[leveloffset=2]
include::fbstreaming/_hqbird-fbstreaming-simple-json-plugin.adoc[leveloffset=2]
