[[hqbird-ocr-udr]]
= OCR-UDR -- функции распознавания текста с изображений

HQbird включает OCR-UDR, который содержит функцию распознавания текста на изображениях.

UDR OCR основан на бесплатной библиотеке распознавания текста Tesseract OCR 4.1, выпущенной по лицензии Apache, версия 2.0.

Чтобы зарегистрировать OCR-UDR, вам необходимо выполнить следующий скрипт:

[source,sql]
----
CREATE OR ALTER FUNCTION GET_OCR_TEXT (
    PIX_DATA BLOB SUB_TYPE BINARY,
    PPI      SMALLINT = NULL)
RETURNS BLOB SUB_TYPE TEXT
EXTERNAL NAME 'ocrudr!getOcrText!eng' ENGINE UDR;

COMMENT ON FUNCTION GET_OCR_TEXT IS
'Recognizing text from images';

COMMENT ON PARAMETER GET_OCR_TEXT.PIX_DATA IS
'Image';

COMMENT ON PARAMETER GET_OCR_TEXT.PPI IS
'Pix Per Inch. Some image formats do not store this information. For scanned
pages are usually 200-300 ppi. The minimum value is 70.';
----

[IMPORTANT]
====
Обратите внимание! В `EXTERNAL NAME` после имени модуля и точки входа через "!" указывается название словаря.

Где `eng` словарь из каталога `tessdata`, который используется для распознавания. Здесь можно указать несколько словарей, например `rus+eng`. Если словарь отсутствует, то используется `eng`.

В дистрибутиве HQBird содержится ограниченное количество словарей. Полный список словарей доступен по адресам: https://github.com/tesseract-ocr/tessdata_best[] (высокое качество распознавания) или https://github.com/tesseract-ocr/tessdata_fast[] (высокая скорость распознавания).
====

Библиотека поддерживает распознавание текста с изображений в форматах PNG, JPEG, GIF.

== Пример использования OCR-UDR

Предположим, у вас есть таблица `DOCS`, в которой хранятся сканы документов, определенная следующим образом:

[source,sql]
----
CREATE TABLE DOCS (
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME       VARCHAR(127) NOT NULL,
    PIC        BLOB SUB_TYPE 0,
    TXT        BLOB SUB_TYPE TEXT,
    PROCESSED  BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT PK_DOCS PRIMARY KEY (ID)
);
----

Изображения для распознавания сохраняются в поле `PIC`, распознанный текст -- в поле `TXT`.

Чтобы распознать текст из одного изображения, вы можете использовать запрос:

[source,sql]
----
SELECT GET_OCR_TEXT(pic, 200) as txt
FROM docs
WHERE docs.id = 2;
----

Следующий запрос распознает текст на изображениях и сохраняет его в поле `TXT`.

[source,sql]
----
UPDATE DOCS
SET TXT = GET_OCR_TEXT(PIC, 200),
    PROCESSED = TRUE
WHERE PROCESSED IS FALSE;
----
