:sectnums!:

[appendix]
[[hqbird-appx-cron-expr]]
= Выражения CRON

Все задания в FBDataGuard имеют настройки времени в формате CRON. CRON -- очень простой и мощный формат для планирования времени выполнения.

== Формат CRON

Выражение CRON представляет собой строку, состоящую из 6 или 7 полей, разделенных пробелами. Поля могут содержать любые разрешенные значения, а также различные комбинации разрешенных специальных символов для этого поля. Поля следующие:

[cols="1,1,1,1", frame="topbot", options="header"]
|===
| Имя поля
| Обязательное
| Допустимые значения
| Допустимые специальные символы


|Секунды
|Да
|0-59
|, - * /

|Минуты
|Да
|0-59
|, - * /

|Часы
|Да
|0-23
|, - * /

|День месяца
|Да
|1-31
|, - * / L W

|Месяц
|Да
|1-12 или JAN-DEC
|, - * /

|День недели
|Да
|1-7 или SUN-SAT
|, - * / L #

|Год
|Нет
|empty, 1970-2099
|, - * /
|===

Таким образом, выражения cron могут быть такими простыми: `\* * * * ? *` или более сложными, например: `0 0/5 14,18,3-39,52 ? JAN,MAR,SEP MON-FRI 2002-2010`

== Специальные символы

* `{asterisk}` ("`все значения`") -- используется для выбора всех значений в поле.
Например, "`{asterisk}`" в поле минуты обозначает "`каждую минуту`".

* `?` ("`нет конкретного значения`") -- полезно, когда вам нужно указать что-то в одном из двух полей, в котором разрешен символ, но не в другом.
Например, если я хочу, чтобы мой триггер сработал в определенный день месяца (скажем, 10-го числа), но меня не волнует, какой это будет день недели. Тогда необходимо поместить "`10`" в поле день месяца и "`?`" в поле день недели. См. пояснительные примеры ниже.

* `-` -- используется для указания диапазонов.
Например, "`10-12`" в поле часы обозначает "`10, 11 и 12 час`".

* `,` -- используется для указания дополнительных значений.
Например, `MON,WED,FRI` в поле день недели обозначает "`Понедельник, Среда и Пятница`".

* `/` -- используется для указания приращений.
Например, "`0/15`" в поле секунды обозначает "`0, 15, 30, и 45 секунду`".
А "`5/15`" в поле секунды обозначает "`5, 20, 35, и 50 секунду`".
Вы также можете указать "`/`" после символа "`{asterisk}`" -- в этом случае "`{asterisk}`" эквивалентна наличию "`0`" до "`/`". "`1/3`" в поле день месяца обозначает "`срабатывать каждые 3 дня начиная с первого дня месяца`".

* `L` ("`last`") -- имеет разное значение в каждом из двух полей, в которых оно разрешено.
Например, значение "`L`" в поле день месяца обозначает "`последний день месяца`" -- 31 января, 28 день Февраля в невисокосные годы.
Если оно используется в поле день недели, то это просто обозначает "`7`" или "`SAT`".
Но если оно используется в поле дня недели после другого значения, то оно означает "`последний xxx день месяца`" -- например "`6L`" обозначает "`последняя Пятница месяца`".
При использовании опции "`L`" важно не указывать списки или диапазоны значений, так как вы получите запутанные результаты.

* `W` ("`weekday`") -- используется для указания дня недели (Понедельник-Пятница) ближайшего к данному дню. (Дня рабочей недели).
Например, если вы указали "`15W`" в качестве значения в поле день месяца, то это обозначает: "`ближайший день недели к 15 числу месяца`".
Таким образом, если 15-е число -- суббота, то триггер сработает в пятницу 14-го.
Если 15-е число выпадает на воскресенье, триггер сработает в понедельник 16-го числа.
Если 15-е число -- вторник, то сработает во вторник 15-го.
Однако если вы укажете "`1W`" в качестве значения для дня месяца, а 1-е число -- суббота, то триггер сработает в понедельник, 3-го числа, так как он не будет "`перепрыгивать`" через границу дня месяца.
Символ "`W`" можно указать только в том случае, если день месяца представляет собой один день, а не диапазон или список.
+
[NOTE]
====
Символы "`L`" и "`W`" также можно объединить в поле день месяца, чтобы получить "`LW`", что переводится как "`последний день недели месяца`".
====

* `#` -- используется для указания "`n-ого`" XXX дня месяца.
Например, значение "`6#3`" в поле дня недели означает "`третью пятницу месяца`" (день 6 = Пятница и "`#3`" = третья пятница месяца). Другие примеры: "`2#1`" = первый понедельник месяца, "`4#5`" = пятая среда месяца.
Обратите внимание, что если вы укажете "`#5`" и в месяце нет пяти заданных дней недели, то в этом месяце триггер не сработает.

[NOTE]
====
Специальные символы и названия дней и месяцев не чувствительны к регистру символов. "`MON`" -- то же самое, что и "`mon`".
====

== Примеры CRON

Вот несколько полных примеров:

[cols="1,1", frame="topbot", options="header"]
|===
| Выражение
| Значение


|`0 0 12 * * ?`
|Запуск в 12:00 (полдень) каждый день.

|`0 15 10 ? * *`
|Запуск в 10:15 каждый день.

|`0 15 10 * * ?`
|Запуск в 10:15 каждый день.

|`0 15 10 * * ? *`
|Запуск в 10:15 каждый день.

|`0 15 10 * * ? 2005`
|Запуск в 10:15 каждый день в течении 2005 года.

|`0 * 14 * * ?`
|Запуск каждую минуту, начиная с 14:00 и заканчивая 14:59, каждый день.

|`0 0/5 14 * * ?`
|Запуск каждые 5 минут, начиная с 14:00 и заканчивая 14:55, каждый день.

|`0 0/5 14,18 * * ?`
|Запуск каждые 5 минут, начиная с 14:00 и заканчивая 14:55, и запуск каждые 5 минут, начиная с 18:00 и заканчивая 18:55, каждый день.

|`0 0-5 14 * * ?`
|Запуск каждую минуту, начиная с 14:00 и заканчивая 14:05, каждый день.

|`0 10,44 14 ? 3 WED`
|Запуск в 14:10 и в 14:44 каждую среду в марте.

|`0 15 10 ? * MON-FRI`
|Запуск в 10:15 каждый понедельник, вторник, среду, четверг и пятницу.

|`0 15 10 15 * ?`
|Запуск в 10:15 15-го числа каждого месяца.

|`0 15 10 L * ?`
|Запуск в 10:15 в последний день каждого месяца.

|`0 15 10 ? * 6L`
|Запуск в 10:15 в последнюю пятницу каждого месяца.

|`0 15 10 ? * 6L 2002-2005`
|Запуск в 10:15 каждую последнюю пятницу каждого месяца в 2002, 2003, 2004 и 2005 годах.

|`0 15 10 ? * 6#3`
|Запуск в 10:15 в третью пятницу каждого месяца.

|`0 0 12 1/5 * ?`
|Запуск в 12:00 (полдень) каждые 5 дней каждого месяца, начиная с первого числа месяца.

|`0 11 11 11 11 ?`
|Запуск каждое 11 ноября в 11:11.
|===

[IMPORTANT]
====
Обратите внимание на эффекты '?' и '*' в полях дня недели и дня месяца!
====

== Замечания

Поддержка указания значения дня недели и дня месяца не является полной (в настоящее время необходимо использовать символ '?' в одном из этих полей).

Будьте осторожны, устанавливая время пожара между полуночью и 1:00 ночи — "`переход на летнее время`" может привести к пропуску или повторению в зависимости от того, перемещается ли время назад или вперед.

Больше информации читайте http://www.quartz-scheduler.org/docs/tutorials/crontrigger.html[]

:sectnums:
