[[hqbird-rsa-udr]]
= RSA-UDR -- функции безопасности для подписания документов и проверки подписей

HQbird включает RSA-UDR, который содержит набор полезных функций безопасности.
Эти функции могут быть полезны для защиты документов (хранящихся в виде VARCHAR, BLOB и даже внешних файлов) с помощью цифровых подписей.

.Важно
[IMPORTANT]
====
RSA-UDR не требуется при использовании Firebird 4.0 и выше, поскольку эти функции встроены.
====

.Внимание!
[NOTE]
====
Чтобы использовать функции RSA-UDR, вам необходимо зарегистрировать их в вашей базе данных с помощью соответствующего SQL скрипта.
Скрипт расположен в `plugin/UDR/crypto.sql`
====

Рассмотрим функции из этой библиотеки и примеры их использования.

[cols="1,1", options="header"]
|===
| Функция
| Описание


|BIN2HEX
|Преобразование двоичного представления в HEX (шестнадцатеричное)

|BIN2HEXB
|Преобразование двоичного BLOB в шестнадцатеричное представление

|CRC32
|Вычисляет контрольную сумму

|CRC32B
|Вычисляет контрольную сумму BLOB

|DECODE_BASE64
|Декодирует из Base64

|DECODE_BASE64B
|Декодирует BLOB из Base64

|ENCODE_BASE64
|Кодирует в Base64

|ENCODE_BASE64B
|Кодирует BLOB в Base64

|HEX2BIN
|Преобразование шестнадцатеричного представления в двоичное

|HEX2BINB
|Преобразование шестнадцатеричного представления в двоичное для BLOB

|MD5
|Вычисляет хэш MD5

|MD5B
|Вычисляет хэш MD5 для BLOB 

|RSA_PUBLIC_KEY
|Генерирует открытый ключ

|RSA_PRIVATE_KEY
|Генерирует закрытый ключ

|RSA_SIGN
|Подписывает объект

|RSA_VERIFY
|Проверяет подпись

|SHA1
|Вычисляет хэш SHA

|SHA1B
|Вычисляет хэш SHA для BLOB

|SHA256
|Вычисляет хэш SHA256

|SHA256B
|Вычисляет хэш SHA256 для BLOB
|===

Рассмотрим на упрощенном примере, как использовать эти функции для подписания какого-либо документа и проверки подписи.

Для простоты мы поместим документ, закрытый ключ, открытый ключ, дайджест (хэш-сумму документа) и подпись в одну таблицу:

[listing]
----
 SQL> show table TBL;

 DOC BLOB segment 80, subtype BINARY Nullable
 DIGEST VARCHAR(32) CHARACTER SET OCTETS Nullable
 SALTLEN INTEGER Nullable
 PRIVATE_KEY VARCHAR(2048) CHARACTER SET OCTETS Nullable
 SIGN VARCHAR(1024) CHARACTER SET OCTETS Nullable
 PUBLIC_KEY VARCHAR(512) CHARACTER SET OCTETS Nullable
 BAD_SIGN VARCHAR(1024) CHARACTER SET OCTETS Nullable
----

Рассмотрим пример:

[listing]
----
 -- Сначала подключимся к базе данных:

 C:\HQbird\Firebird30>isql localhost:c:\temp\rsatest.fdb -user SYSDBA -pass masterkey
 Database: localhost:c:\temp\rsatest.fdb, User: SYSDBA

 -- а затем проверим, что функции зарегистрированы
 SQL> show functions;
 Global functions

 Function Name Invalid Dependency, Type
 ================================= ======= =====================================
 RSA_PRIVATE_KEY
 RSA_PUBLIC_KEY
 RSA_SIGN
 RSA_VERIFY
 SHA256


 -- очистим тестовую таблицу
 SQL>delete from tbl
 SQL>commit;

 -- генерируем приватный ключ и записываем
 -- записываем его в таблицу TBL (обычно приватный ключ хранится в секретном месте)

 SQL>insert into tbl(PRIVATE_KEY) values(rsa_private_key(1024));

 -- генерируем публичный ключ
 SQL>update tbl set PUBLIC_KEY = rsa_public_key(PRIVATE_KEY);

 -- создаём BLOB документ
 SQL>update TBL set DOC='testtesttest';

 -- и вычисляем его дайджест
 SQL>update tbl set digest = sha256(doc);

 –- подписываем документ и сохраняем его подпись
 SQL>update tbl set sign = rsa_sign(digest, PRIVATE_KEY, 8);

 -- проверка подписи
 SQL> select RSA_VERIFY(SIGN, DIGEST, PUBLIC_KEY, SALTLEN) from tbl;

 RSA_VERIFY
 ==========
 <true>
 -- как видите подпись действительна

 –- изменяем документ (BLOB)
 SQL> update TBL set DOC='testtesttest222';

 -- перевычисляем его дайджест
 SQL> update tbl set digest = sha256(doc);

 -- проверяем подпись
 SQL> select rsa_verify(sign, digest, PUBLIC_KEY, 8) from tbl;

 RSA_VERIFY
 ==========
 <false>
 -- мы видим что защищённый документ был изменён
----

Примеры использования функций `BIN2HEX` и `HEX2BIN`

[listing]
----
 SQL> set list;
 SQL> select bin2hex('Test string') from rdb$database;

 BIN2HEX 5465737420737472696E67

 SQL> select cast (hex2bin('5465737420737472696E67') as varchar(32))
 CON> from rdb$database;

 CAST     Test string
----

== Как использовать функции безопасности и преобразования RSA-UDR

В основном функции RSA-UDR позволяют подписывать электронные документы всех типов (DOC, PDF, XML, JPG, PNG и т. д.), а затем обнаруживать несанкционированные изменения.

Функции преобразования упрощают преобразования BIN->HEX и HEX->BIN, а также кодирование и декодирование Base64.
