[[hqbird-overview]]
= Обзор HQbird

== Что такое HQbird

HQbird -- дистрибутив СУБД Firebird для предприятий от IBSurgeon Software (www.ib-aid.com[https://www.ib-aid.com]), включающий в себя дополнительные функции, преимущественно повышающие производительность для больших и высоконагруженных баз данных, а также набор инструментов для организации полного цикла обслуживания баз данных без администратор базы данных (включая инструменты для оптимизации производительности, мониторинга, локального и облачного резервного копирования, а также восстановления в случае сбоев).

HQbird ускоряет работу больших баз данных (от 50 ГБ до 2 ТБ) и позволяет компаниям управлять большими базами данных, не требуя выделенного администратора баз данных для нескольких серверов или снижая расходы на поддержку многих (сотни и тысячи) серверов Firebird.

Минимальные аппаратные требования для HQbird -- 8 ГБ ОЗУ и 4 ядра. Первая версия HQbird была выпущена в 2015 году, текущая версия -- HQbird 2024.

== Как Firebird связан с HQbird?

Проще говоря, HQbird -- это корпоративная версия СУБД Firebird с открытым исходным кодом. Следуя традиции open-source проектов, мы называем Firebird "`ванильной`" версией: точно так же существует "`ванильная`" версия PostgreSQL и коммерческие версии EnterpriseDB, PostgresPro и т. д.

HQbird не является "`другой`" базой данных с точки зрения совместимости с Firebird: нет необходимости делать резервное копирование-восстановление при переключении между HQbird и Firebird, не нужно переписывать SQL или менять клиентские приложения.

Без каких-либо проблем вы можете установить HQbird и ванильную версию Firebird параллельно на одном сервере, работать с файлом базы данных с помощью HQbird, затем переключиться на ванильный Firebird, и наоборот.

100% совместимость HQbird с ванильным Firebird -- самая важная особенность HQbird!

Практически все функции, разработанные для HQbird, попадают в Firebird в пределах 1-2 версий: например, репликация появилась в HQbird версии 2.5, а в ванильном Firebird -- в версии 4.0, пул внешних соединений был разработан в HQbird 3.0 и появился в Firebird 4.0, возможности многопоточного резервного копирования, восстановления и sweep появились начиная с HQbird 2.5, и стали доступны в ванильном Firebird 5.0 и т. д.

Помимо нового функционала, ошибки, исправленные в HQbird, также исправлены в соответствующих версиях ванильного Firebird.

Также компания IBSurgeon Software проводит публичное тестирование Firebird и HQbird на предмет надежности и производительности: результаты тестирования публикуются на сайте https://www.firebirdtest.com[www.firebirdtest.com].

== Какова цена HQbird?

Постоянная лицензия на 1 сервер стоит 899 долларов США. В комплект также входит 1 лицензия на сервер реплик.

Какова будет цена HQbird для компании, которой необходимо использовать не 1 или 2 сервера, а несколько сотен или даже тысяч установок?
Если количество серверов превышает 20, покупка постоянных лицензий (899 долларов США/сервер) становится слишком дорогой. Вот почему мы предлагаем безлимитную подписку HQbird для компаний-разработчиков программного обеспечения.

Неограниченная подписка HQbird для компаний-разработчиков программного обеспечения стоит 1200 долларов США в месяц (или 13450 долларов США в год с авансовым платежом) за годовой контракт (обратите внимание, что региональные цены могут отличаться).

Это специальная лицензия для компаний-разработчиков программного обеспечения, которая позволяет устанавливать и использовать неограниченное количество копий HQbird вместе с бизнес-приложениями (ERP, CRM и т. д.), производимыми компанией.

Например, если у компании 40 клиентов, то подписка будет стоить 1200 долларов США в месяц, то есть примерно 30 долларов США на одного клиента в месяц. Если у компании-разработчика программного обеспечения 400 клиентов, то стоимость 1 клиента в месяц составит 3 доллара в месяц.

== Что нового в HQbird 2024

HQbird 2024 -- это новая крупная версия, в которой добавлена поддержка Firebird 5.0 и ряд важных функций:

* Замена запросов "на лету"
* Улучшена технология Firebird Streaming:
** Добавлен контрольный файл, с тем же форматом, который используется для репликации в Firebird 4 и выше
** Добавлено восстановление службы `fb_streaming` после сбоя (сегменты репликации не удаляются до тех пор пока транзакции начатые в них не будут завершены или откачены. После сбоя происходит повтор транзакций, которые не успели зафиксироваться).
** Добавлен новый плагин Kafka CDC (Change Data Capture)

Кроме того, HQbird 2024 по-прежнему предлагает расширенные функции репликации, пул внешних подключений, пул подготовленных операторов и другие функции, необходимые при работе с большими базами данных под высокой нагрузкой.

<<<

== Матрица функций

Ниже представлена матрица функций и уровень их поддержки в различных версиях Firebird, поставляемых в составе HQBird.

[cols="1,4,1,1,1,1,2", frame="all", options="header"]
|===
| №
| Функция
| V5.0
| V4.0
| V3.0
| V2.5
| Уровень

|1
|Высокопроизводительная встроенная репликация
|X
|X
|X
|X
|Сервер

|2
|Замена запросов "на лету"
|X
|X
|X
|X
|Сервер

|3
|Плагины для доступа к ODBC/MySQL через оператор `EXECUTE STATEMENT ON EXTERNAL`
|X
|X
|X
|
|Плагин

|4
|Кэширование BLOB во временном пространстве
|X
|X
|X
|X
|Сервер

|5
|Улучшения в оптимизаторе для JOIN и больших сортировок
|X
|X
|X
|
|Сервер

|6
|Кеш подготовленных запросов
|X
|X
|X
|
|Сервер

|7
|Firebird Streaming (плагины Kafka CDC, RabbitMQ и др.)
|X
|X
|
|
|Плагин

|8
|Полнотекстовый поиск
|X
|X
|X
|
|Плагин

|9
|Многопоточный backup/restore/sweep, создание индексов
|X
|X
|X
|X
|Сервер

|10
|Параллельное чтение согласованных данных
|X
|X
|X
|X
|Сервер

|11
|Пул внешних соединений
|X
|X
|X
|
|Сервер

|12
|Шифрование
|X
|X
|X
|
|Плагин

|13
|Автоматическая коррекция `firebird.conf` (`DefaultDbCachePages`)
|X
|X
|X
|X
|Сервер

|14
|Расширенный мониторинг производительности (трассировка, MON, блокировки, ЦП, ОЗУ, диск)
|X
|X
|X
|X
|Инструмент

|15
|Мониторинг запросов с большими сортировками
|X
|X
|X
|X
|Сервер

|16
|Регистрация и настройка репликации для множества баз данных с помощью инструментов командной строки.
|X
|X
|X
|X
|Инструмент

|17
|Автоматизация backup,restore и backup/restore
|X
|X
|X
|X
|Инструмент

|18
|Передача резервных копий, сегментов репликации через FTP в облако
|X
|X
|X
|X
|Инструмент

|19
|Расширенное обслуживание базы данных: правильная сборка мусора и многое другое.
|X
|X
|X
|X
|Инструмент

|20
|Поддержка множества экземпляров Firebird
|X
|X
|X
|X
|Инструмент

|21
|Тихая установка в Window и Linux
|X
|X
|X
|X
|Инструмент

|22
|Инструменты для анализа статистики
|X
|X
|X
|X
|Инструмент

|23
|Инструмент для анализа соединений/транзакций/потребления памяти/операций ввода-вывода
|X
|X
|X
|X
|Инструмент

|24
|Инструменты починки БД
|X
|X
|X
|X
|Инструмент

|25
|Оптимизированные конфигурации
|X
|X
|X
|X
|Инструмент

|===

<<<

== Краткое описание функций HQBird

=== Высокопроизводительная встроенная репликация

HQbird включает встроенную репликацию для создания отказоустойчивых систем на базе баз данных Firebird:

* Репликация баз данных с более чем 1500 подключениями.
* Асинхронная репликация с задержкой 1-30 секунд,
* Синхронная репликация без задержек,
* Никаких триггеров или других изменений в схеме не требуется.
* Автоматическое распространение изменений DDL,
* Онлайн-реинициализация реплик.
* Встроенные инструменты для передачи изменений репликации, проверка переданных сегментов репликации.

Нативная репликация настраивается через специальный плагин, с возможностью исключения записей без PK/UK на уровне плагина.

HQbird имеет полный инструментарий для организации передачи сегментов для асинхронной репликации для схем "`1-к-1`" или "`1-ко-многим`", с автоматической настройкой, передачей и проверкой сегментов репликации через сокеты или FTP. В HQbird есть инструменты командной строки для настройки баз данных для массовой репликации, выбора баз данных в папке или во вложенных папках.

=== Замена запросов "на лету"

Если у вас есть приложение с недоступными или отсутствующими исходными кодами, то HQbird может помочь вам изменить тексты несовместимых или наиболее ресурсоемких SQL-запросов "`на лету`", а значит, помочь оптимизировать производительность или произвести миграцию приложения на новую версию Firebird. Замена легко настраивается, и реализуется парами файлов, содержащих текст исходного и заменяемого запросов.

С помощью расширенного мониторинга вы можете найти SQL-запросы, вызывающие проблемы, а затем настроить их замену, даже без доступа к исходному коду приложения. Замененный запрос появится в  трассировке и MON$ таблицах с новым текстом.

=== Плагины для работы с внешними базами данных MySQL или через ODBC

HQbird имеет плагины внешних источников данных для ODBC и MySQL. Используя эти плагины, можно выполнять команды `EXECUTE STATEMENT ON EXTERNAL` с запросами к источнику данных MySQL или ODBC, чтобы читать данные из внешних источников данных или записывать данные во внешние источники данных.

Плагины поддерживают входные параметры и корректное отображение типов данных (однако в случае ODBC это зависит от конкретной реализации драйвера).

Пример внешнего подключения ниже:

[source,sql]
----
execute block
returns (
  emp_no bigint,
  birth_date date,
  first_name varchar(14),
  last_name varchar(16),
  gender char(1),
  hire_date date
)
as
  declare dsn_mysql varchar(128);
begin
  dsn_mysql = ':mysql:host=localhost;port=3306;database=employees;user=root';
  for
    execute statement q'{
select
  emp_no,
  birth_date,
  first_name,
  last_name,
  gender,
  hire_date
from employees
order by birth_date desc limit 5
}'
    on external dsn_mysql
    as user null password 'sa'
    into
      emp_no, birth_date, first_name, 
      last_name, gender, hire_date
  do
    suspend;
end
----

Подробнее см. <<hqbird-eds-other-dbms>>

=== Кэширование BLOB во временном пространстве

HQbird может кэшировать BLOB-объекты во временном пространстве, чтобы ускорить операции с BLOB (на +15%-200% быстрее, чем в обычном Firebird) и предотвратить рост файла базы данных в случае ошибочных операций с BLOB.

HQbird использует дополнительный параметр `BlobTempSpace` в `firebird.conf` для управления этой функцией.

Вариант кэширования может быть:

* 0 -- отключено,
* 1 -- включено для PSQL (по умолчанию),
* 2 —- включено для всех операций с BLOB.

=== Улучшения в оптимизаторе для JOIN и больших сортировок

==== LeftJoinConversion / OuterLeftConversion

HQbird может автоматически преобразовывать неявные внутренние соединения в явные для лучшей оптимизации в версиях 3 и 4.

Чтобы активировать эту функцию, измените настройку `LeftJoinConversion` в `firebird.conf` на `true`. HQbird в версии 5.0 поддерживает опцию `OuterLeftConversion`, доступную в стандартной версии Firebird 5.0.

==== SortDataStorageThreshold / InlineSortThreshold

HQbird может оптимизировать запросы, включающие большие операции сортировки. В версиях 2.5 и 3.0 вы можете использовать параметр SortDataStorageThreshold, для активации метода доступа `Refetch`. 

В "`ванильной`" версии Firebird 4.0 этот параметр переименован в `InlineSortThreshold`. Обычно мы рекомендуем установить для `SortDataStorageThreshold` значение 8192 или 16384 байта.

=== Кеш подготовленных запросов

Эта функция может повысить производительность повторяющихся запросов, особенно при использовании пула соединений (PHP и т. д.).

Кэш хранит определенное количество подготовленных запросов в памяти каждого соединения. HQbird имеет этот кеш в версиях 3.0 и 4.0, и вы можете настроить его с помощью параметра `DSQLCacheSize` (по умолчанию -- 0, т. е. отключено).

В "`ванильной`" версии Firebird 5.0 есть аналогичная функция, регулируемая опцией `MaxCompiledCache`, которая измеряется в мегабайтах, по умолчанию -- 2 МБ.

=== Firebird Streaming (плагины Kafka CDC, RabbitMQ и др.)

Firebird Streaming -- это технология, которая отслеживает изменения в базе данных и отправляет их в другую систему, например Kafka, файлы JSON, RabbitMQ, плагин полнотекстового поиска и т. д.

HQbird предлагает плагин для сбора измененных данных (Change Data Capture), основанный на репликации. Плагин создает поток изменений, отражающий фиксации/откаты транзакций.

HQbird предоставляет готовые плагины для Kafka, RabbitMQ, JSON файлов, а также поддерживает их настройку для любого места назначения. CDC полезен для обработки очередей, асинхронной отправки предупреждений и копирования изменений в другие системы (например, конвейеры бизнес-аналитики или обработки данных).

Плагин CDC поставляется по запросу. Для получения дополнительной информации обратитесь в службу поддержки IBSurgeon (support@ib-aid.com).

Подробнее см. <<hqbird-fbstreaming>>

=== Полнотекстовый поиск

Полнотекстовый поиск -- это технология, позволяющий искать любое слово или фразу в большой коллекции документов или данных. Полнотекстовый поиск отличается от поиска на основе метаданных или части текста, который может не отражать полное значение или контекст запроса. Полнотекстовый поиск использует полнотекстовый механизм, такой как Lucene, для выполнения поиска и возврата результатов.

IBSurgeon Full Text Search UDR -- это набор внешних процедур и функций (UDR), которая интегрирует Lucene с Firebird. IBSurgeon Full Text Search UDR позволяет выполнять полнотекстовый поиск в таблицах Firebird в полях varchar и BLOB с использованием движка Lucene.

Эта UDR доступен с открытым исходным кодом, но HQbird предоставляет настраиваемый плагин на основе Firebird Streaming для оперативного обновления.

Более подробная информация: https://www.firebirdsql.org/en/full-text-search-udr/[]

=== Многопоточный backup/restore/sweep, создание индексов

HQbird реализует многопоточные операции обслуживания (sweep), резервного копирования, восстановления и создания индекса. Поддерживаются Firebird 2.5, 3.0 и 4.0, эта функциональность также появилась в "`ванильной`" версии Firebird 5.0.

Формат файлов резервных копий такой же, как и в "`ванильном`"  Firebird. На тестовом сервере с 8 ядерным процессором и SSD мы имеем следующие результаты (по сравнению с 1 потоком);

* Резервное копирование -- в 4-6 раз быстрее.
* Восстановление -- в 2-4 раза быстрее на процессорах с 8 ядрами и твердотельных накопителях.
* sweep -- в 4-6 раз быстрее.

Реальное ускорение зависит от процессора, дисковой подсистемы сервера и структуры базы данных. Установите HQbird в пробном режиме (до 30 дней) и проверьте, какие результаты будут на вашем сервере!

Более подробную информацию и результаты испытаний можно найти здесь: https://ib-aid.com/articles/firebird-gbak-backuptips-and-tricks#110hqbirdbackup.

=== Параллельное чтение согласованных данных

HQbird, начиная с версии 2.5, поддерживает две важные функции:

. функция `make_dbkey()`, позволяющая читать таблицу, разбитую на блоки (по страницам указателей PP),
. и "`shared snapshot`" для SNAPSHOT транзакций, который позволяет читать согласованные данные в разных соединениях.

Эти функции помогают добиться параллельного чтения больших наборов данных и ускорить операции экспорта в 2-10 раз (например, для экспорта BI или для конвейера данных). Эти функции также доступны в "`ванильной`" Firebird, начиная с версии 4.0.

* Больше деталей читайте в статье: https://ib-aid.com/articles/parallel-reading-of-data-in-firebird[]
* Пример приложения с исходными кодами: https://github.com/IBSurgeon/FBCSVExport[]

=== Пул внешних соединений

В HQbird есть пул внешних подключений для Firebird 2.5, 3.0, и этот пул также доступен в "`ванильной`" версии, начиная с Firebird 4.0.

Пул внешних подключений позволяет выполнять инструкции `EXECUTE STATEMENT ON EXTERNAL` с меньшими затратами на повторное соединение с внешней базой данных.

Эта функция контролируется в файле `firebird.conf` с помощью параметров `ExtConnPoolSize` и `ExtConnPoolLifeTime`.

С точки зрения приложения не требуется никаких дополнительных действий для использования или неиспользования -- оно включается или выключается в конфигурации сервера и полностью прозрачно для приложений. Также можно отключить сборку мусора для запросов, выполняемых во внешних соединениях. Это регулируется параметром конфигурации `ExtConnNoGarbageCollect`.

Подробнее см. <<hqbird-performance-extconn-pool>>

=== Шифрование

HQbird поддерживает шифрование с помощью плагина Encryption Framework. Основные особенности:

. Плагин шифрования БД (доступен по запросу) для версий 3, 4, 5 под Windows и Linux. Это комплексная и быстрая платформа плагинов шифрования с AES256. Потеря производительности составляет от 4% до 20%, в зависимости от оперативной памяти и конфигурации.
. Поддержка многопоточной работы (для промежуточных приложений, с подключением к нескольким базам данных).
. Отправка ключей через `fbclient.dll` для реализации шифрования без изменения приложения. Если у вас есть инструмент базы данных, не поддерживающий передачу ключей, или стороннее приложение, ключ можно отправить через `fbclient.dll` со специальной конфигурацией.
. Окно ввода пароля для `fbclient.dll` в Windows и ввода пароля на терминале в Linux.

По запросу мы можем предоставить примеры клиентских приложений на различных языках, таких как Delphi, NET, Java, PHP, {cpp} и т.д.

=== Автоматическая коррекция `firebird.conf` (`DefaultDbCachePages`)

Неправильная настройка `DefaultDbCachePages` в `firebird.conf`, `databases.conf` или в заголовке базы данных -- распространенная ошибка конфигурации, которая часто случается во время миграции между версиями. Например, это могут быть слишком большие значения Page Buffers в заголовке базы данных для Classic или SuperClassic или слишком низкие для SuperServer.

HQbird автоматически исправит неправильные настройки в файлах `firebird.conf` и `databases.conf` и перезапишет их, если конфигурация не подходит для выбранной архитектуры.

=== Расширенный мониторинг производительности (трассировка, MON, блокировки, ЦП, ОЗУ, диск)

Расширенный мониторинг производительности в HQbird -- это функция, которая позволяет вам отслеживать и анализировать производительность ваших баз данных Firebird (версии 5.0, 4.0, 3.0, 2.5) в режиме реального времени. Он собирает данные из различных источников, таких как Trace API, таблицы MON$, таблица блокировок, транзакции, использование ЦП и ОЗУ, и отображает их в графической и табличной формах. Вы можете увидеть общие тенденции производительности, а также детализировать каждую минуту, запрос или транзакцию.

Вы также можете выявить проблемы с производительностью, такие как медленные и частые запросы, длительные транзакции, скачки в таблице блокировок и т.д., а также просмотреть их планы и статистику.

* Более подробная информация: https://ib-aid.com/monitoring-in-hqbird[]
* Видео: https://www.youtube.com/watch?v=GuRmHZ8ErZ4[]

=== Мониторинг запросов с большими сортировками

Эта функция помогает устранять неполадки в запросах, которые создают большие отчеты, в которых необходимо отсортировать множество записей. HQbird может отслеживать запросы и операции, которые создают файлы сортировки, превышающие заданный размер. При обнаружении такого запроса его текст записывается в файл `firebird.log`.

Для настройки используется параметр `TempSpaceLogThreshold` в `firebird.conf`, который определяет размер файла сортировки для мониторинга.

=== Управление и настройка репликации для множества баз данных с помощью инструментов командной строки

Если в папке хранится много баз данных, и вы хотите зарегистрировать их все в HQbird для настройки репликации, в HQbird v2024 есть новая команда командной строки для создания файла JSON из папки с регистрационной информацией, который можно использовать для массовой регистрации.

Что касается реплик, существует специальная версия HQBird Central для реплик, которая позволяет хранить сотни реплик (с разных серверов) на одном сервере. HQbird Central для реплик поставляется по запросу.

=== Автоматизация backup,restore и backup/restore

. Резервные копии: HQbird реализует все типы резервных копий со сложным или простым планированием (все можно делать онлайн с подключенными пользователями):
.. Проверенная резервная копия с помощью `gbak.exe`. Традиционный формат резервного копирования Firebird, когда Firebird считывает каждую запись в базе данных, гарантируя ее работоспособность. В HQbird (версии 2.5-5.0) проверенное резервное копирование выполняется очень быстро за счет поддержки многопоточности. HQbird реализует ротацию проверенных резервных копий, сжатие и тестовое восстановление. HQbird рассчитывает необходимое пространство для резервных копий, чтобы гарантировать, что резервная копия поместится в свободное пространство, и создает подробные журналы для всех операций.
.. Инкрементное резервное копирование. Быстрое резервное копирование на физическом уровне, при котором копируются измененные страницы данных. HQbird предлагает 3 схемы резервного копирования: простое еженедельное трехуровневое резервное копирование, расширенное многоуровневое резервное копирование (до 5 уровней) и резервное копирование дампа для создания копии базы данных. Файлы резервных копий ротируются, рассчитывается необходимое пространство.
. Восстановление
.. Восстанавливает базы данных из резервных копий. HQbird позволяет восстановить базу данных из FBK. Это особенно важно для облачных экземпляров, когда FBK загружается в облачный экземпляр, поэтому нет необходимости подключаться к консоли сервера (т. е. по ssh или RDP).
.. Тестовое восстановление как часть проверенного процесса резервного копирования. Вы можете выполнить проверку восстановления из новой резервной копии, это будет выполнено как часть процесса восстановления из проверенной резервной копии.
.. Плановое восстановление. Возможна организация планового восстановления проверенных (gbak) резервных копий и/или инкрементных (nbackup) резервных копий, например, в рамках инфраструктуры резервного копирования.
. Автоматическое резервное копирование-восстановление. Поддержка полного цикла резервного копирования-восстановления, как планового, так и по запросу. HQbird выполнит полное резервное копирование и восстановление безопасным и быстрым способом: остановит всех пользователей, выполнит резервное копирование и восстановление, разрешит пользователей. Старая копия базы данных будет сохранена. В случае возникновения проблемы процесс будет отменен. Если места будет недостаточно, резервное копирование-восстановление не запустится.

С HQbird вы всегда можете отслеживать свои резервные копии и не терять их, независимо от того, сколько у вас баз данных и где они находятся.

=== Передача резервных копий, сегментов репликации через FTP в облако

HQbird может передавать резервные копии (или другие файлы по маске) через FTP, сокеты или на Amazon S3 (требуется плагин, который доступен по запросу).

HQbird также имеет встроенный FTP-сервер и сервер сокетов с простой настройкой.

=== Расширенное обслуживание базы данных: правильная сборка мусора и многое другое

Чрезмерное количество версии записей, также известные как мусорные версии, значительно замедляют работу баз данных Firebird. HQbird реализует правильное сочетание операций sweep и "`мягкого`" завершения длительных write транзакций и позволяет избежать частого резервного копирования/восстановления базы данных. С HQbird рекомендуется выполнять резервное копирование/восстановление не чаще одного раза в год.

Обслуживание также может включать пересчет статистики индексов и проверку работоспособности индексов, а также проверку работоспособности метаданных.

=== Поддержка множества экземпляров

HQbird позволяет установить несколько экземпляров Firebird разных версий на одном сервере. Это упрощает миграцию с одной версии на другую. HQbird для Windows по умолчанию устанавливает все поддерживаемые версии Firebird (5.0, 4.0, 3.0, 2.5), каждый экземпляр имеет свой порт. Во время установки вы можете выбрать установку только одной версии или нескольких версий.

Чтобы установить HQbird для Linux с несколькими экземплярами, используйте единый установщик (это новая функция HQbird v2024) и укажите, какие версии вам нужны.

=== Тихая установка в Window и Linux

Самый быстрый способ установки HQbird -- использовать автоматическую установку из командной строки.

В приведенном ниже примере мы установим HQbird с Firebird 3.0 в `c:\HQbird`, конфигурация будет в `c:\HQbirdData\config`, выходные файлы будут в `c:\HQbirdData\output`.

----
HQbirdServer2024.exe /VERYSILENT /SP- /TYPE="hqbird30x64" /DIR="C:\HQbird2020" /CONFIGDIR=C:\HQBirdData\config /OUTPUTDIR=C:\HQBirdData\output
----

Смотри также:

* Как установить на Linux: <<hqbird-install-linux>>
* Подробно о тихой установке: <<hqbird-install-silent>>

=== Инструменты для анализа статистики

Пакет администратора HQbird (он работает в Windows) включает в себя Database Analyst, инструмент, который помогает пользователю подробно анализировать статистику базы данных Firebird и выявлять возможные проблемы с производительностью базы данных, ее обслуживанием и взаимодействием приложения с базой данных. IBAnalyst графически отображает статистику базы данных Firebird в удобной для пользователя форме и выявляет следующие проблемы:

* Фрагментация таблиц и BLOB
* Версии записей
* Сборка мусора
* Неэффективные индексы

Подробнее см. <<hqbird-struct-analyze>>

=== Инструмент для анализа соединений/транзакций/потребления памяти/операций ввода-вывода

HQbird MonLogger -- это инструмент для анализа вывода таблиц мониторинга в Firebird, поиска проблем с медленными SQL-запросами, неправильно спроектированных транзакций (длительных транзакций, транзакций с неправильным уровнем изоляции и т. д.), а также выявления проблемных приложений.

MonLogger может подключиться к базе данных Firebird с проблемами производительности и определить причину медленности: какое-то пользовательское подключение, медленный SQL-запрос или длительная транзакция?

MonLogger поддерживает Firebird 2.1, 2.5, 3.0, 4.0 и 5.0 -- для более старых версий Firebird или InterBase используйте FBScanner (не входит в состав HQbird, приобретается отдельно).

MonLogger может показать вам:

* Топ соединений с наибольшим количеством операций ввода-вывода, неиндексированными и индексированными чтениями.
* Топ операторов SQL с наибольшим количеством операций ввода-вывода, неиндексированных и индексированных операций чтения.
* Проблемные транзакции: длительные транзакции, транзакции с ошибочным уровнем изоляции, транзакции чтения/записи и сопутствующая информация: когда они начались, какие приложения запустили эти транзакции, с какого IP-адреса и т. д.
* Соединения и операторы с наиболее интенсивными действиями по сборке мусора.
* Соотношение чтения/записи, соотношение INSERT/UPDATE/DELETE и многое другое.

=== Инструменты починки БД

HQbird включает лицензию FirstAID, инструмента восстановления для Firebird. IBSurgeon FirstAID -- это инструмент, который может автоматически диагностировать и восстанавливать поврежденные базы данных Firebird или InterBase. Он может восстанавливать повреждения, которые не могут исправить ни `gbak`, ни `gfix`. Поддерживаемые версии: Firebird 1.0, 2.0, 2.1, 2.5, 3.0, 4.0, 5.0, InterBase с 4.0 по 2020.

Он использует свой слой для низкоуровневого доступа к базе данных без использования движков InterBase или Firebird, поэтому он может выполнять настоящие "`хирургические`" операции и восстанавливать вашу базу данных, когда все другие стандартные инструменты (`gfix` и `gbak`) не могут.

=== Оптимизированные конфигурации

HQbird по умолчанию поставляется с оптимизированной конфигурацией, позволяющей максимально эффективно использовать ресурсы мощных серверов и виртуальных машин. Чтобы улучшить конфигурацию HQbird, вы можете использовать "`Калькулятор конфигурации`" для Firebird, где вы можете выбрать HQbird, чтобы получить базовую оптимизированную конфигурацию для вашей системы здесь: https://cc.ib-aid.com/democalc.html[].

Обратите внимание, что Калькулятор создает консервативные конфигурации, и для создания индивидуальной конфигурации вам необходимо отслеживать и анализировать журналы производительности. IBSurgeon может помочь вам создать идеальную конфигурацию в контексте оптимизации/конфигурации/аудита для Firebird: https://ib-aid.com/en/firebird-interbase-performance-optimization-service/[]
