[[hqbird-split-udr]]
= SPLIT-UDR -- процедуры разбиения строк по разделителю

HQbird включает в себя SPLIT-UDR, который содержит набор полезных хранимых процедур. Эти процедуры могут быть полезны для разделения строки (хранящейся в виде VARCHAR или BLOB) по разделителю.

.Замечание
[NOTE]
====
Чтобы использовать функции SPLIT-UDR, вам необходимо зарегистрировать их в вашей базе данных с помощью соответствующего SQL скрипта. Скрипт расположен в `plugin/UDR/split-udr.sql`
====

Для удобства процедуры разделения текста по разделителю упакованы в пакет `SPLIT_UTILS`.

Рассмотрим процедуры из этой библиотеки и примеры их использования.

[cols="1,1", options="header"]
|===
| Имя процедуры
| Описание

| `SPLIT_BOOLEAN`
| Разбивает строку по разделителю и возвращает `BOOLEAN` значения.

| `SPLIT_SMALLINT`
| Разбивает строку по разделителю и возвращает `SMALLINT` значения.

| `SPLIT_INT`
| Разбивает строку по разделителю и возвращает `INTEGER` значения.

| `SPLIT_BIGINT`
| Разбивает строку по разделителю и возвращает `BIGINT` значения.

| `SPLIT_STR`
| Разбивает строку по разделителю и возвращает `VARCHAR(8191)` значения.

| `SPLIT_DATE`
| Разбивает строку по разделителю и возвращает `DATE` значения.

| `SPLIT_TIME`
| Разбивает строку по разделителю и возвращает `TIME` значения.

| `SPLIT_TIMESTAMP`
| Разбивает строку по разделителю и возвращает `TIMESTAMP` значения.

| `SPLIT_DOUBLE`
| Разбивает строку по разделителю и возвращает `DOUBLE PRECISION` значения.

|===

Первый аргумент этих процедур — это `BLOB` с подтипом `TEXT`, второй — строка типа `VARCHAR(10)`.
Тип выходного значения зависит от имени процедуры.

Рассмотрим простые примеры использования этих процедур.

[listing]
----
SQL> select cast(out_str as varchar(10)) from SPLIT_UTILS.split_str('abc##defg##aa', '##');

CAST
==========
abc
defg
aa

SQL> select out_int from SPLIT_UTILS.split_int('1,2,3,4,5', ',');

     OUT_INT
============
           1
           2
           3
           4
           5
----

Кроме того, SPLIT-UDR также содержит процедуры разделения текста на токены (текст разбивается по нескольким разделителям). Эти процедуры объявляются следующим образом:

[source,sql]
----
CREATE OR ALTER PROCEDURE SPLIT_WORDS (
    IN_TXT        BLOB SUB_TYPE TEXT CHARACTER SET UTF8,
    IN_SEPARATORS VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL)
RETURNS (
    WORD VARCHAR(8191) CHARACTER SET UTF8)
EXTERNAL NAME 'splitudr!strtok' ENGINE UDR;

CREATE OR ALTER PROCEDURE SPLIT_WORDS_S (
    IN_TXT        VARCHAR(8191) CHARACTER SET UTF8,
    IN_SEPARATORS VARCHAR(50) CHARACTER SET UTF8 DEFAULT NULL)
RETURNS (
    WORD VARCHAR(8191) CHARACTER SET UTF8)
EXTERNAL NAME 'splitudr!strtok_s' ENGINE UDR;
----

Входные параметры:

* `IN_TXT` - входной текст типа `BLOB SUB_TYPE TEXT` или `VARCHAR (8191)`
* `IN_SEPARATORS` - список разделителей (строка с символами-разделителями), если не указан, то используются разделители " \n\r\t,.?!:;/\|<>[]{}()@#$%^&*-+='"~`"

Пример:

[source,sql]
----
  SELECT
    w.WORD
  FROM DOCS
  LEFT JOIN SPLIT_WORDS(DOCS.CONTENT) w ON TRUE
  WHERE DOCS.DOC_ID = 4
----
