:sectnums!:

[appendix]
[[hqbird-appx-web-api]]
= HQbird web API

HQbird FBDataGuard позволяет автоматизировать множество задач администрирования, запускать их по расписанию или по требованию из Web консоли DataGuard.

В некоторых случаях приложениям требуется запускать административные задачи, которые уже реализованы в HQbird FBDataGuard. Для разработчиков таких приложений HQbird FBDataGuard предоставляет Web API для запуска задач, настроенных в FBDataGuard.

Запускаемые задачи могут быть уровня агента, сервера или базы данных. Для успешного запуска задачи она должна быть "разрешена" (enabled в конфигурации). Для задач уровня базы данных, необходимо знать регистрационный идентификатор базы.

Все задачи запускаются через один и тот же обработчик, который представляет собой Web API по HTTP протоколу методом GET.
URL этого обработчика имеет следующий вид:

----
<schema>://<host>:<port>/agent/runnow?<parameters>

<parameters> ::= <parameter>[&<parameter> [&<parameter> ...]]

<parameter> ::= <param_name>=<param_value>
----

Здесь 

- `<schema>` - схема (в нашем случае протокол http или https);
- `<host>` - имя хоста или IP адрес на котором запущен HQbird FBDataGuard;
- `<port>` - номер порта на котором работает служба HQbird FBDataGuard;
- `<param_name>` - имя параметра;
- `<param_value>` - значение параметра, которое должно быть закодировано с помощью URL кодирования описанного в RFC 3986.

Для конфигурации по умолчанию этот URL принимает следующий вид:

----
http://127.0.0.1:8082/agent/runnow?<parameters>
----

Для запуска задач требуются следующий параметры:

- `src` - источник (уровень задачи);
- `job` - имя задачи;
- дополнительные параметры, зависящие от задачи, например `lvl=1`;
- опциональный параметр, которым выступает некоторое, уникальное, целое число (метка времени) - которая предотвращает кэширования результата браузерами.

Источник `src` должен иметь полную форму вида пути к задаче, примеры:

----
/agent/jobs/check-agent-space
----

или

----
/agent/servers/hqbirdsrv/jobs/check-server-log
----

или

----
/agent/servers/hqbirdsrv/databases/a8005009-c850-42ec-8def-133bd8405253/jobs/lockprint
----

В зависимости от содержимого источника (параметр `src`) определяет уровень задачи:

* если источник имеет вид `/agent/servers/hqbirdsrv/databases/<database_guid>/jobs/...`, где `<database_guid>` - это идентификатор базы данных, то это задача уровня базы данных. В примере выше база данных имеет идентификатор `a8005009-c850-42ec-8def-133bd8405253`. Идентификатор базы данных можно узнать по соответствующему имени каталога в файловом дереве конфигурации DataGuard;
* если источник имеет вид `/agent/servers/hqbirdsrv/jobs/...`, то это задача уровня уровня сервера;
* если источник имеет вид `/agent/jobs/...`, то это задача уровня уровня агента.


Приведём несколько примеров запуска задач по требованию. В этих примерах предполагается, что FBDataGuard работает на узле `127.0.0.1:8082`.

.Вызов задачи проверки лога сервера
[example]
====
URL задачи:

----
http://127.0.0.1:8082/agent/runnow?r=1727043834949&src=%2Fagent%2Fservers%2Fhqbirdsrv%2Fjobs%2Fcheck-server-log&job=check-server-log
----

Здесь

- `src=/agent/servers/hqbirdsrv/jobs/check-server-log`
- `job=check-server-log`
- `r=1727043834949` - параметр для предотвращения кэширования браузером повторных запросов.

Сервер в ответ вернёт строку в виде json с указанием времени, тэга, пути к файлу конфигурации задачи и возможным сообщением об ошибке.

Пример ответа:

[source%autofit,json]
----
{
    "Queried": "1727044250754",
    "Tag": "check-server-log@[ hqbirdsrv / * ]",
    "JobConfigFile": "E:\\HQBirdData\\config\\agent\\servers\\hqbirdsrv\\jobs\\check-server-log\\job.properties",
    "ErrorMessage": ""
}
----

Пример ответа с сообщением об ошибке на попытку запуска отключённой задачи:

[source%autofit,json]
----
{
    "Queried":"1727044440296",
    "Tag":"check-replica-log@[ hqbirdsrv / * ]",
    "JobConfigFile":"E:\\HQBirdData\\config\\agent\\servers\\hqbirdsrv\\jobs\\check-replica-log\\job.properties",
    "ErrorMessage":"Disabled job cannot be started! Enable job first! \nJob id: \"check-replica-log@[ hqbirdsrv / * ]\""
}
----
====


Далее будут приведены примеры запуска задачи для базы данных, зарегистрированной в Dataguard под идентификатором Dataguard ID: 2409230136_EMPLOYEE3_FDB.

.Вызов sweep для базы данных
[example]
====
URL задачи:

----
http://127.0.0.1:8082/agent/runnow?r=1727044656798&src=%2Fagent%2Fservers%2Fhqbirdsrv%2Fdatabases%2F2409230136_EMPLOYEE3_FDB%2Fjobs%2Fcronsweep&job=cronsweep
----

Здесь

- `src=/agent/servers/hqbirdsrv/databases/2409230136_EMPLOYEE3_FDB/jobs/cronsweep`
- `job=cronsweep`
====

.Запуск задачи nbackup (версии simple) уровня 2
[example]
====
URL задачи:

----
http://127.0.0.1:8082/agent/runnow?r=1727045317158&src=%2Fagent%2Fservers%2Fhqbirdsrv%2Fdatabases%2F2409230136_EMPLOYEE3_FDB%2Fjobs%2Fnbackup&job=nbackup&lvl=2
----

Здесь

- `src=/agent/servers/hqbirdsrv/databases/2409230136_EMPLOYEE3_FDB/jobs/nbackup`
- `job=nbackup`
- `lvl=2` - задаёт уровень бакапа (2).
====

.Запуск задачи nbackup (версии advanced) уровня 3
[example]
====
URL задачи:

----
http://127.0.0.1:8082/agent/runnow?r=1727045751740&src=%2Fagent%2Fservers%2Fhqbirdsrv%2Fdatabases%2F2409230136_EMPLOYEE3_FDB%2Fjobs%2Fnbackup3&job=nbackup3&lvl=3
----

Здесь

- `src=/agent/servers/hqbirdsrv/databases/2409230136_EMPLOYEE3_FDB/jobs/nbackup3`
- `job=nbackup3`
- `lvl=3` - задаёт уровень резервной копии (3). Является некоторым излишеством, передаётся браузером/вебконсолью, но не используется сервером и может быть пропущен, т.к. 
уровни advanced nbackup реализованы отдельными потоками с уникальными именами, то есть задачи nbackup0..nbackup4 - и для них уровни в lvl должны соответствовать уровню в пути/имени.
====

Запуски задач по требованию протоколируются в журнал FBDataGuard.

Полный список путей/имён задач можно реконструировать из каталога действующей в конкретной версии в конфигурации DataGuard -- в разных версиях DataGuard они могут отличаться так как задачи менялись, удалялись или добавлялись новые.

== Отладка

Следующие URL помогут при отладке команд:

* Запуск команд
+
----
http://localhost:8082/static/config.html#hqbirdsrv
----

* Просмотр API в необработанном виде
+
----
http://localhost:8082/agent/
----

Сервисную страницу можно открыть (откроется в новой вкладке) непосредственно из веб-окна консоли FbDataGuard, если кликнуть левой кнопкой мыши с зажатой клавишей `Ctrl` по тексту версии DataGuard в левом нижнем углу страницы.
