[[hqbird-performance]]
= Улучшения производительности

[[hqbird-performance-extconn-pool]]
== Пул внешних подключений

HQbird поддерживает пул внешних подключений для Firebird 2.5 и Firebird 3. Стандартная сборка Firebird 4.0 и выше поддерживает создание внешних пулов соединений "`из коробки`".

Пул внешних подключений позволяет выполнять инструкции `EXECUTE STATEMENT ON EXTERNAL` с меньшими затратами на повторное соединение с внешней базой данных.

[NOTE]
====
Обратите внимание: этот пул выделяется для каждого экземпляра Firebird.
====

Эта функция настраивается в файле `firebird.conf`:

[source,conf]
----
# ============================
# Settings of External Connections Pool
# ============================

# Set the maximum number of inactive (idle) external connections to retain at
# the pool. Valid values are between 0 and 1000.
# If set to zero, pool is disabled,
# i.e. external connection is destroyed immediately after the use.
#
# Type: integer
#
#ExtConnPoolSize = 0

# Set the time before destroying inactive external connection, seconds.
# Valid values are between 1 and 86400.
#
# Type: integer
#
#ExtConnPoolLifeTime = 7200
----

С точки зрения приложения не требуется никаких дополнительных действий для использования или неиспользования -- пул включается или отключается в конфигурации сервера и абсолютно незаметно для приложений.

Для управления пулом существуют следующие команды:

* изменение размера пула
+
[listing,subs=+quotes]
----
ALTER EXTERNAL CONNECTIONS POOL SET SIZE _N_
----
+
Пример: эта команда устанавливает размер пула на 190 подключений.
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL SET SIZE 190
----
* изменение времени жизни неактивного соединение в пуле
+
[listing,subs=+quotes]
----
ALTER EXTERNAL CONNECTIONS POOL
SET LIFETIME _N_ {SECOND | MINUTE | HOUR}
----
+
Пример: эта команда ограничивает время жизни соединения в пуле до 1 часа.
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL SET LIFETIME 1 HOUR
----
* очистить все соединения в пуле
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL CLEAR ALL
----
* очистить самое старое соединение в пуле
+
[source,sql]
----
ALTER EXTERNAL CONNECTIONS POOL CLEAR OLDEST
----

Для получения информации о состоянии пула были введены новые контекстные переменные. Следующий пример демонстрирует их использование

[source,sql]
----
SELECT
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_SIZE') AS INT) AS POOL_SIZE,
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_IDLE_COUNT') AS INT) AS POOL_IDLE,
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_ACTIVE_COUNT') AS INT) AS POOL_ACTIVE,
  CAST(RDB$GET_CONTEXT('SYSTEM', 'EXT_CONN_POOL_LIFETIME') AS INT) AS POOL_LIFETIME
FROM RDB$DATABASE;
----

<<<

== Кеш подготовленных запросов

В HQbird есть возможность улучшить производительность движка Firebird (версии 4.0 и 5.0) в случае большого количества частых и быстрых SQL-запросов: кэширование подготовленных операторов SQL на стороне сервера. Начиная с Firebird 5.0 эта функция доступна в стандартной сборке "`из коробки`".

=== Кеш подготовленных запросов в Firebird 3.0 и 4.0

Эту функцию можно включить в `firebird.conf` с помощью параметра `DSQLCacheSize`:

[source,conf]
----
# Size of DSQL statements cache.
# Maximum number of statements to cache.
# Use with care as it is per-attachment and could lead to big memory usage.
# Value of zero disables caching.
# Per-database configurable.
# Type: integer
#DSQLCacheSize = 0
----

Это число указывает, сколько последних запросов для каждого подключения к базе данных необходимо кэшировать.

Чтобы применить новое значение, потребуется перезапуск Firebird.

По умолчанию `DSQLCacheSize` равен 0, что означает выключен. Мы рекомендуем осторожно включать его: начните со значений, таких как 4, 8, 16, чтобы найти лучший эффект производительности.

[NOTE]
====
Обратите внимание: включение кэширования подготовленных операторов увеличивает использование памяти.
====

=== Кеш подготовленных запросов в Firebird 5.0

В Firebird 5.0 кеш подготовленных запросов был переработан и включён в "`ванильную`" сборку.

Кеш подготовленных запросов управляется параметром `MaxStatementCacheSize` в `firebird.conf`.

[source,conf]
----
# ----------------------------
# Maximum statement cache size
#
# The maximum amount of RAM used to cache unused DSQL compiled statements.
# If set to 0 (zero), statement cache is disabled.
#
# Per-database configurable.
#
# Type: integer
#
#MaxStatementCacheSize = 2M
----

По умолчанию кеш подготовленных запросов включен. Для его отключения необходимо установить параметр `MaxStatementCacheSize` в 0.

<<<

== TempSpaceLogThreshold: мониторинг запросов с большими сортировками и BLOB

HQbird имеет новый параметр в `firebird.conf` in Firebird 2.5, Firebird 3.0, Firebird 4.0 и Firebird 5.0:

[source,conf]
----
TempSpaceLogThreshold=1000000000 #bytes
----

Когда Firebird видит этот параметр, он записывает тексты запросов в `firebird.log` для запросов, которые производят большие сортировки (запросы с `GROUP BY`, `ORDER BY` и т. д.).


Когда такой запрос создаст файл сортировки, размер которого превышает указанный порог, в `firebird.log` появится следующее сообщение:

----
SRV-DB1	Wed Nov 28 21:55:36 2018
	Temporary space of type "sort" has exceeded threshold of 1000000000 bytes.
	Total size: 10716980736, cached: 1455423488 bytes, on disk: 9263120384 bytes.
	Query: select count(*) from (select lpad('',1000,uuid_to_char(gen_uuid())) s
	       from rdb$types a,rdb$types b, rdb$types c  order by 1)
----

*Total size*:: общий размер файла сортировки

*Cached*:: часть сортировки, уместившаяся во временное пространство (задается параметром `TempCacheLimit`)

*On disk*:: часть сортировки, которая была сохранена во временный файл, который может быть кэширован в памяти ОС или сохранен на диске (в папке, указанной параметром `TempDirectories`, или в временной папке по умолчанию)

Для очень больших BLOB в файле `firebird.log` появится следующее сообщение

----
SRV-DB1	Tue Nov 27 17:35:39 2018
	Temporary space of type "blob" has exceeded threshold of 500000000 bytes.
	Total size: 500377437, cached: 0 bytes, on disk: 501219328 bytes.
----

Используйте `TempSpaceLogThreshold` для поиска неоптимизированных запросов с большой сортировкой и большими BLOB-объектами. Начиная с Firebird 3.0 в нём также будет сообщаться о больших хеш-таблицах (возникают при HASH JOIN).

Если вы столкнулись с такими запросами, оптимизируйте их либо путем изменения самого SQL-запроса, либо попробуйте включить параметр `SortDataStorageThreshold`.

<<<

== SortDataStorageThreshold: REFETCH вместо SORT для широких наборов данных

HQbird поддерживает новый метод оптимизации REFETCH. Стандартная сборка Firebird версии 4.0 и выше поддерживает этот алгоритм оптимизации "`из коробки`".

В HQbird появился новый параметр `SortDataStorageThreshold` в `firebird.conf` (Firebird 3.0+):

[source,conf]
----
SortDataStorageThreshold=16384 # bytes
----

[NOTE]
====
Начиная с версии 4.0 этот параметр был переименован в `InlineSortThreshold`.

[source,conf]
----
InlineSortThreshold=16384 # bytes
----
====

Если размер записи, возвращаемой SQL-запросом, будет больше указанного порога, Firebird будет использовать другой подход для сортировки наборов записей: REFETCH вместо SORT.

Например, у нас есть следующий запрос

[source,sql]
----
select tdetl.name_detl
    ,tmain.name_main
    ,tdetl.long_description
from tdetl
join tmain on tdetl.pid=tmain.id
order by tdetl.name_detl
----

со следующим планом выполнения:

----
Select Expression
    -> Sort (record length: 32860, key length: 36)
        -> Nested Loop Join (inner)
            -> Table "TMAIN" Full Scan
            -> Filter
                -> Table "TDETL" Access By ID
                    -> Bitmap
                        -> Index "FK_TABLE1_1" Range Scan (full match)
----

В этом случае размер каждой сортируемой записи составляет 32860+36 байт. Это может привести к созданию очень больших файлов сортировки, которые будут записаны на диск, и выполнение запроса может замедлиться.

С параметром `SortDataStorageThreshold=16384` или `InlineSortThreshold=16384` Firebird будет использовать метод доступа REFETCH, гв котором сортируется только ключ, а данные перечитываются из базы данных:

----
Select Expression
    -> Refetch
        -> Sort (record length: 76, key length: 36)
            -> Nested Loop Join (inner)
----

Такой подход позволяет существенно (в 2-5 раз) ускорить запросы с сортировкой очень широких наборов записей (обычно это тяжелые отчеты).

.Обратите внимание!
[NOTE]
====
Не рекомендуется устанавливать `SortDataStorageThreshold` (`InlineSortThreshold`) меньше чем 2048 байт.
====

<<<

[[hqbird-performance-multi-threaded]]
== Многопоточные sweep, backup, restore

В HQbird появилась возможность многопоточного выполнения очистки, резервного копирования и восстановления, что ускоряет их работу от 2х до 6 раз (в зависимости от конкретной базы). Многопоточные операции работают в HQbird для Firebird 2.5, 3.0 и 4.0 на любых архитектурах — Classic, SuperClassic, SuperServer. Для Firebird 5.0 многопоточные операции доступны в "`ванильной`" версии из коробки.

Чтобы включить многопоточное выполнение, утилиты командной строки `gfix` и `gbak` имеют параметр `–par _n_`, где `n` -- количество потоков, которые будут задействованы в конкретной операции. На практике выбор числа n следует соотносить с количеством доступных ядер процессора.

Примеры:

* `gfix –sweep database –par 8 ...`
* `gbak –b database backup –par 8 ...`
* `gbak –c backup database –par 8 ...`

Кроме того, чтобы ограничивать количество рабочих потоков и устанавливать их число по умолчанию, в `firebird.conf` введены два новых параметра, которые влияют только на sweep и restore, но не на резервное копирование:

[source,conf]
----
# ============================
# Settings for parallel work
# ============================
#  Limit number of parallel workers for the single task. Per-process.
#  Valid values are from 1 (no parallelism) to 64. All other values
#  silently ignored and default value of 1 is used.
MaxParallelWorkers = 64
----

Пример: если вы установите `MaxParallelWorkers = 10`, вы сможете выполнять

* run `gfix –sweep database –par 10`
* run `gfix –sweep database –par 5` and `gbak –c –par 5 ...`

То есть всего будет использовано не более 10 потоков.
В случае превышения (например, если вы установили 6 потоков на sweep и 6 потоков на restore), для процесса, превышающего лимит, будет выведено сообщение "`No enough free worker attachments`").

Таким образом, чтобы включить многопоточные возможности`sweep и restore, вы должны установить параметр `MaxParallelWorkers` в `firebird.conf`.

[source,conf]
----
MaxParallelWorkers = 64
----

и перезапустить Firebird.

`ParallelWorkers` по умолчанию устанавливает количество потоков, используемых для sweep и restore, если не указана опция `–par _n_`.

[source,conf]
----
#  Default number of parallel workers for the single task. Per-process.
#  Valid values are from 1 (no parallelism) to MaxParallelWorkers (above).
#  Values less than 1 is silently ignored and default value of 1 is used.
#
ParallelWorkers = 1
----

Например, если `ParallelWorkers = 8`, то запуск

[source,bash]
----
gfix –sweep
----

без опции `-par _n_` будет использоваться 8 потоков для параллельного выполнения sweep.

[IMPORTANT]
====
До Firebird 5.0 в HQbird при восстановлении заполнение таблиц из резервной копии всегда выполняется в одном потоке, а распараллеливается только создание индексов. Таким образом, ускорение восстановления зависит от количества индексов в базе данных и их размера. Также параметр `ParallelWorkers` автоматически влияет на создание индексов, выполняемых операциями `CREATE INDEX` и `ALTER INDEX... ACTIVE`.

Начиная с Firebird 5.0 заполнение таблиц при восстановлении тоже используется параллелизм.
====

Как упоминалось выше, эти параметры не влияют на резервное копирование. Многопоточность резервного копирования регулируется только параметром `–par _n_` в командной строке:

* `gbak –b –par 6 ...`
* `gbak –b –par 8 –se ...`

[IMPORTANT]
====
Если база данных находится в состоянии single shutdown, когда к базе данных разрешено только 1 соединение, то в версии 2.5 sweep, и резервное копирование с `-par _2_` или более будут вызывать ошибку через несколько секунд после запуска:

* sweep -- connection lost to database
* backup -- ERROR: database ... shutdown (по протоколу xnet строка с этим сообщением не будет отображаться в журнале резервного копирования)

Это связано с тем, что для этих операций требуется соответствующее количество подключений к базе данных, более 1.

В 3.0 только резервное копирование выдает ошибку "`ERROR: database ... shutdown`", sweep будет работать

Многопоточное восстановление Firebird 2.5, 3.0, 4.0 и 5.0 создает базу данных в режиме shutdown multi, поэтому такие ошибки не возникают. Однако существует риск подключения к базе данных в процессе восстановления других приложений от `SYSDBA` или владельца.
====

.Замечания
[NOTE]
====
* Новые параметры в `firebird.conf` влияют только на очистку и восстановление. Чтобы упростить администрирование и устранить двусмысленность, рекомендуется всегда явно указывать параметр `-par n` для `gfix` и `gbak`, если вам нужно выполнять многопоточные операции sweep, восстановления и резервного копирования. Например, если вы установите `ParallelWorkers = 4` и не укажете `-par n`, то sweep и восстановление будут использовать 4 потока по умолчанию, а резервное копирование будет использовать 1 поток, поскольку не использует значения из `firebird.conf` ни локально, ни с помощью `-se`.
* Прирост производительности не обязательно зависит от количества ядер процессора и их соответствия заданному значению `–par n`. Это зависит от количества ядер, архитектуры Firebird и производительности дисковой подсистемы (IOPS). Поэтому оптимальное значение `–par n` для вашей системы необходимо подобрать экспериментально.
====

<<<

[[hqbird-blob-append]]
== Функция BLOB_APPEND

Обычный оператор `||` (конкатенация) с аргументами BLOB создает временный BLOB для каждой пары аргументов с BLOB. Это может привести к чрезмерному потреблению памяти и увеличению размера файла базы данных. Функция `BLOB_APPEND` предназначена для объединения BLOB-объектов без создания промежуточных BLOB-объектов.

Результирующий BLOB-объект функции `BLOB_APPEND` остается открытым для записи, а не закрывается сразу после заполнения данными. Т.е. в такой BLOB можно добавлять столько раз, сколько необходимо. Движок помечает такой объект новым внутренним флагом `BLB_close_on_read` и автоматически закрывает его при необходимости.

*Доступен в*: DSQL, PSQL.

.Синтаксис:
[listing,subs=+quotes]
----
BLOB_APPEND(<blob> [, <value1>, ... <valueN]>
----

.Parameters of BLOB_APPEND function
[cols="1,2", options="header"]
|===
| Параметр
| Описание

| blob
| BLOB или NULL.

| value
| Значение любого типа.
|===


*Возвращаемый тип*: временный не закрытый BLOB (т.е. открытый для записи), помеченный флагом
`BLB_close_on_read`.

Входные аргументы:

* Первый аргумент BLOB или `NULL`. Возможны следующие варианты:
** `NULL`:  создаётся новый временный не закрытый BLOB с флагом `BLB_close_on_read`
** постоянный BLOB (из таблицы) или временный уже закрытый BLOB:
создаст новый пустой незакрытый BLOB с флагом `BLB_close_on_read` и к нему будет добавлено содержимое первого BLOB
** временный незакрытый BLOB с флагом `BLB_close_on_read`: будет использоваться далее
* остальные аргументы могут быть любого типа. Для них определено следующее поведение:
** `NULL` игнорируется
** не-BLOB будут преобразованы в строку и добавлены к содержимому результата
** BLOB, при необходимости транслитерируются в набор символов первого аргумента, а их содержимое добавляется к результату.

Функция BLOB_APPEND возвращает временный незакрытый BLOB с флагом BLB_close_on_read. Это либо новый BLOB, либо тот же самый, что и в первом аргументе. Таким образом, серия операций типа `blob = BLOB_APPEND (blob, ...)` приведет к созданию не более одного BLOB (если вы не попытаетесь добавить BLOB к самому себе). Этот BLOB-объект будет автоматически закрыт механизмом, когда клиент попытается прочитать его, назначить таблице или использовать в других выражениях, требующих чтения содержимого.

[NOTE]
====
Проверка BLOB-объекта на наличие значения `NULL` с использованием оператора `IS [NOT] NULL` не приводит к его чтению, поэтому временный BLOB-объект с флагом `BLB_close_on_read` не будет закрыт во время такой проверки.
====

[source,sql]
----
execute block
returns (b blob sub_type text)
as
begin
  -- создаёт временный незакрытый BLOB
  -- и запишет в него строку из второго аргумента
  b = blob_append(null, 'Hello ');
  -- добавляет две строки во временный BLOB без его закрытия
  b = blob_append(b, 'World', '!');
  -- сравнение BLOB со строкой закроет его, потому что для этого вам нужно прочитать BLOB
  if (b = 'Hello World!') then
  begin
  -- ...
  end
  -- создаст временный закрытый BLOB, добавив к нему строку
  b = b || 'Close';
  suspend;
end
----

[TIP]
====
Используйте функции `LIST` и `BLOB_APPEND` для объединения BLOB. Это позволит сэкономить потребление памяти, дисковый ввод-вывод и предотвратить рост базы данных из-за создания множества временных BLOB-объектов при использовании операторов конкатенации.
====

[example]
====
Допустим, вам нужно собрать JSON на стороне сервера. У нас есть PSQL пакет `JSON_UTILS` с набором функций для преобразования примитивных типов данных в нотацию JSON. Тогда построение JSON с использованием функции `BLOB_APPEND` будет выглядеть так:

[source,sql]
----
EXECUTE BLOCK
RETURNS (
    JSON_STR BLOB SUB_TYPE TEXT CHARACTER SET UTF8)
AS
  DECLARE JSON_M BLOB SUB_TYPE TEXT CHARACTER SET UTF8;
BEGIN
  FOR
      SELECT
          HORSE.CODE_HORSE,
          HORSE.NAME,
          HORSE.BIRTHDAY
      FROM HORSE
      WHERE HORSE.CODE_DEPARTURE = 15
      FETCH FIRST 1000 ROW ONLY
      AS CURSOR C
  DO
  BEGIN
    SELECT
      LIST(
          '{' ||
          JSON_UTILS.NUMERIC_PAIR('age', MEASURE.AGE) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('height', MEASURE.HEIGHT_HORSE) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('length', MEASURE.LENGTH_HORSE) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('chestaround', MEASURE.CHESTAROUND) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('wristaround', MEASURE.WRISTAROUND) ||
          ',' ||
          JSON_UTILS.NUMERIC_PAIR('weight', MEASURE.WEIGHT_HORSE) ||
          '}'
      ) AS JSON_M
    FROM MEASURE
    WHERE MEASURE.CODE_HORSE = :C.CODE_HORSE
    INTO JSON_M;

    JSON_STR = BLOB_APPEND(
      JSON_STR,
      IIF(JSON_STR IS NULL, '[', ',' || ascii_char(13)),
      '{',
      JSON_UTILS.INTEGER_PAIR('code_horse', C.CODE_HORSE),
      ',',
      JSON_UTILS.STRING_PAIR('name', C.NAME),
      ',',
      JSON_UTILS.TIMESTAMP_PAIR('birthday', C.BIRTHDAY),
      ',',
      JSON_UTILS.STRING_VALUE('measures') || ':[', JSON_M, ']',
      '}'
    );
  END
  JSON_STR = BLOB_APPEND(JSON_STR, ']');
  SUSPEND;
END
----

Аналогичный пример с использованием обычного оператора конкатенации `||` на порядок медленнее и выполняет в 1000 раз больше операций записи на диск.
====

<<<

[[hqbird-performance-left-to-inner]]
== Преобразование LEFT joins в INNER

HQbird позволяет преобразовывать `LEFT JOIN` в `INNER JOIN`, если условие `WHERE` нарушает правила внешнего соединения.

[NOTE]
====
Начиная с Firebird 5.0 это функциональность доступна в "`ванильной`" версии Firebird.
====

Пример:

[source,sql]
----
SELECT *
FROM T1 LEFT JOIN T2 ON T1.ID = T2.ID
WHERE T2.FIELD1 = 0
----

В этом случае условие `T2.FIELD1 = 0` эффективно удаляет все "`поддельные NULL`" строки `T2`, поэтому результат тот же, что и для `INNER JOIN`. Однако оптимизатор вынужден использовать порядок соединения T1->T2, хотя мог бы также рассмотреть T2->T1. Имеет смысл обнаружить этот случай во время обработки соединения и заменить `LEFT` на `INNER` перед началом оптимизации.

В первую очередь это предназначено для улучшения автоматически генерируемых (например, ORM) запросов.

[NOTE]
====
Эта оптимизация не будет включена, если фильтруется значение `NULL`, например

[source,sql]
----
SELECT *
FROM T1 LEFT JOIN T2 ON T1.ID = T2.ID
WHERE T2.ID IS NULL
----

или

[source,sql]
----
SELECT *
FROM T1 LEFT JOIN T2 ON T1.ID = T2.ID
WHERE T2.ID IS NOT NULL
----
====

<<<

[[hqbird-performance-lwmonitoring]]
== Легковесный мониторинг

Легковесный мониторинг основан на реализации трейс-плагина, который обновляет мониторинговые счётчики в реальном времени. Счётчики содержатся в общей памяти, это позволяет эффективно работать в режиме Classic Server. Обновление счётчиков не связано с какими-либо блокировками, поэтому максимально эффективно. Размер общей памяти фиксирован и по-умолчанию равен 256КБ, это позволяет накапливать информацию о 512 БД с 1-6 коннектами к каждой или о 1-й БД с 3580 коннектов. Фиксированный размер общей памяти также позволяет (в основном) безблокировочную работу со счётчиками. Изменить размер общей памяти можно, задав в конфигурации плагина новое значение для параметра `MemorySize` (см. пример ниже).

На данный момент поддерживается небольшое количество счётчиков. Мониторинг собирает информацию о двух видах объектов - база данных (БД) и коннект. На уровне БД есть отдельный набор счётчиков для данных о завершившихся коннектах. Это позволяет поддерживать непрерывно накапливаемую информацию о данной БД.

=== Служба легковесного мониторинга

Для получения информации мониторинга создан новый сервис:

[source,cpp]
----
#define isc_action_svc_lwmonitoring	  32	// Lightweight monitoring
----

Сервис имеет два параметра. Первый указывает -- какую операцию нужно выполнить. В данный момент это единственная операция "`выполнить запрос`":

[source,cpp]
----
#define isc_spb_lwm_query			1
----

В свою очередь, реализовано 4 вида запросов, о них чуть ниже. Для указания, какой из запросов нужно выполнить, следует указать его номер (1-4) в качестве целочисленного параметра для `isc_spb_lwm_query`.

Второй параметр -- имя БД, не обязательный. Указывается с помощью давно известного тега `isc_spb_dbname`. Если этот параметр задан, то запрос мониторинга ограничивается указанной БД, иначе -- возвращается информация про все известные на данный момент БД.

=== Запросы к легковесному мониторингу

Опишем 4 вида запросов и что они возвращают.

Все запросы возвращают данные в виде текста, по одной строке на каждый элемент. Элементом может быть инф-ция о БД, о коннекте или агрегирующая информация. Тест отформатирован как JSON -- для облегчения парсинга и лёгкого изменения в будущих версиях.

Все запросы в первой строке возвращают строку вида

[source,json]
----
{"idQuery": 1, "tsQuery": "2024-04-17T00:17:58"}
----

где

* `idQuery`	-- номер (ИД) запроса;
* `tsQuery` -- таймстамп времени начала выполнения запроса, используется локальное время сервера и распространённый формат ISO-8601.

==== Запрос 1: суммарная информация об известных БД и коннектах

Всегда возвращает одну строку вида

[source,json]
----
{"cntDb": 1, "activeAtt": 1, "goneAtt": 0}
----

где

* `cntDb` -- количество БД;
* `activeAtt` -- количество активных коннектов;
* `goneAtt` -- количество завершившихся коннектов.

==== Запрос 2: список БД

Возвращает несколько строк вида

[source,json]
----
{"dbName": "SECURITY2.FDB", "activeAtt": 1, "goneAtt": 2}
----

где

`dbName` -- имя файла БД;
`activeAtt` -- количество активных коннектов;
`goneAtt` -- количество завершившихся коннектов.

==== Запрос 3: суммарная информация об коннектах каждой БД

Возвращает несколько строк вида

[source,json]
----
{"dbName": "SECURITY2.FDB", "activeAtt": 1, "goneAtt": 0, "doneTran": 1, "activeTran": 0, "prepReq": 0, "execReq": 0, "activeReq": 0}
----

где

`dbName` -- имя файла БД;
`activeAtt` -- количество активных коннектов;
`goneAtt` -- количество завершившихся коннектов;
`doneTran` -- количество завершившихся транзакций;
`activeTran` -- количество активных транзакций;
`prepReq` -- количество препарированных запросов;
`execReq` -- количество выполненных запросов;
`activeReq` -- количество активных запросов.

Новые счётчики:

`rowsFetched` -- количество строк данных, полученных приложением;
`execTime` -- время выполнения запросов;
`errors` -- количество ошибок, полученных приложением;
`fetches` -- количество фетчей;
`reads` -- количество чтений страниц;
`marks` -- количество марок (выполняется перед изменением страницы);
`writes` -- количество записей страниц.

==== Запрос 4: подробная информация о каждом коннекте и каждой БД

Возвращает несколько строк вида

[source,json]
----
{"dbName": "SECURITY2.FDB", "activeAtt": 1, "goneAtt": 0} <1>

{"idAtt": 0, "pidAtt": 0, "doneTran": 0, "activeTran": 0, "prepReq": 0, "execReq": 0, "activeReq": 0} <2>

{"idAtt": 13925, "pidAtt": 11188, "doneTran": 1, "activeTran": 0, "prepReq": 0, "execReq": 0, "activeReq": 0} <2>
----

где строки вида (1) описывают БД и строки вида (2) описывают коннекты к этой БД. +
После каждой строки про БД (1) идёт минимум одна строка вида (2) с коннектами именно к этой БД.

* `idAtt` -- connection_id, или 0 для суммарной информации о завершившихся коннектах;
* `pidAtt` -- ID серверного процесса, обслуживающего данный коннект.

Если в процессе выполнения запроса возникает ошибка, то возвращается либо исключение в статус-векторе, либо как данные сервиса в формате:

[source,json]
----
{"errorMsg" : "Error text"}
----

например

[source,json]
----
{"errorMsg" : "Unknown query: 5"}
----

=== Примеры вызова сервиса лёгкого мониторинга

[source,bash]
----
fbsvcmgr service_mgr action_lwmonitoring lwm_query 1
----

[source,bash]
----
fbsvcmgr host:service_mgr action_lwmonitoring lwm_query 4 dbname employee
----

=== Конфигурирование сервиса лёгкого мониторинга

В `firebird.conf` добавлен параметр с именем плагина лёгкого мониторинга

[source,conf]
----
MonitoringPlugin =
----

по умолчанию, плагин не задан и мониторинг не производится. Имя плагина, реализованного для HQBird -- `fblwmon`, т.е. для использования лёгкого мониторинга нужно указать в `firebird.conf`

[source,conf]
----
MonitoringPlugin = fblwmon
----

Сам плагин включён в сборку HQBird и расположен в каталоге `plugins`.

Также можно задать параметры самого плагина в его собственной конфигурации. На данный момент поддерживается один параметр:

* `MemorySize` -- размер общей памяти плагина в байтах.

Конфигурация плагина задаётся стандартным способом (см. `README.plugins.html`), например непосредственно в `plugins.conf`:

[source,conf]
----
Plugin = fblwmon
{
	Config = lwmConfig
}

Config = lwmConfig
{
	# default 256KB
	MemorySize = 1M
}
----

=== Ограничение на количество одновременных коннектов

На основе сервиса лёгкого мониторинга реализовано встроенное ограничение количества одновременных коннектов. Ограничение работает на уровне количества коннектов к данной БД, но само значение ограничения одинаково для всех БД (HQ 2.5 не имеет per-database) настроек. Значения для ограничения задаются в `firebird.conf` двумя целочисленными параметрами:

[source,conf]
----
WarnCountAttachments = 0
MaxCountAttachments = 0
----

Ограничение проверяется в момент коннекта и не учитывает создаваемый коннект. Для проверки применяется значение счётчика активных коннектов к данной БД:

* если `AttCount >= WarnCountAttachments and AttCount < MaxCountAttachments`, то коннект разрешается, но в `firebird.log` помещается сообщение вида
+
----
Database XXX: number of attachments is above warning level (N >= W)
----

* если `AttCount >= MaxCountAttachments`, то коннект не разрешается, клиенту выдаётся сообщение
+
----
Statement failed, SQLSTATE = HY000
Number of attachments exceeds allowed maximum
----
+
и в `firebird.log` помещается сообщение вида
+
----
Database XXX: number of attachments is above maximum level (N >= M)
----

Не проверяются коннекты к `security.db`, служебные коннекты и коннекты с тегом `isc_dpb_no_db_triggers` в DPB.

Если `WarnCountAttachments = 0`, то предупреждения не выдаются.

Если `MaxCountAttachments = 0`, то коннекты не запрещаются.

Для того, чтобы ограничение работало, необходимо установить и настроить плагин лёгкого мониторинга (см. выше).

== Настройки для работы с таблицами мониторинга

При выполнении запроса с участием любой таблицы мониторинга делается так называемый моментальный снимок состояния системы. Для этого активность во всех соединениях прерывается и они сбрасывают свои счётчики и состояние в общую память. Создание моментального снимка состояния системы не является бесплатным -- чем больше соединений и чем они активнее, тем дольше выполняется запрос к таблицам мониторинга. В Firebird 5.0 мониторинг стал ещё дороже, поскольку появилась новая таблица `MON$COMPILED_STATEMENT`, которая по сути является содержимом кеша копилированных запросов всех соединений.

Если количество соединений к базе данных превышает 500, то запросы к таблицам мониторинга могут выполняться достаточно долго и сильно нагружать систему. Но в большинстве случаев запрос производится не ко всем таблицам мониторинга, а "`платить`" приходится также, как будто запрос используется все таблицы `MON$`. В HQbird 2024R2 появились дополнительные параметры конфигурации, которые позволяет отключить заполнение некоторых `MON$` таблиц, облегчая запросы мониторинга.

* `FillMonCompiledStatements` -- заполнять ли данные для таблицы `MON$COMPILED_STATEMENTS`. По умолчанию значение равно `true`.
* `FillMonStatements` -- заполнять ли данные для таблицы `MON$STATEMENTS`. По умолчанию значение равно `true`.
* `FillMonCallStack` -- заполнять ли данные для таблицы `MON$CALL_STACK`. По умолчанию значение равно `true`.

Данные настройки применимы к каждой БД индивидуально, то есть вы можете установить их как `firebird.conf`, та и в `databases.conf`. Они доступны только при использовании Firebird 5.0.

== `CREATE TABLE ... AS (SELECT ...)`

В HQbird 2024R2 при использовании Firebird 5.0.4 доступен новый DDL оператор `CREATE TABLE ... AS (SELECT ...)`.

Он позволяет создать таблицу со структурой, производной от запроса `SELECT`, и, при необходимости, заполнить её данными из этого запроса.

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE [GLOBAL TEMPORARY] TABLE <table_name>
    [(column_name [, ...])]
AS (<select>)
[WITH [NO] DATA]
[ON COMMIT PRESERVE | DELETE ROWS]
----

Столбцы для новой таблицы формируются на основе запроса `<select>` так же, как и для оператора `CREATE VIEW`. Имена столбцов могут быть заданы явно с помощью списка имен. Количество элементов в списке имен и в списке `<select>` должно совпадать. Новые столбцы наследуют только тип данных и атрибут `NOT NULL`. Любое выражение, вычисляемое поле и другое в списке `<select>` будет представлено как одно постоянное поле. Атрибут `identity` также игнорируется.

Необязательная опция `WITH [NO] DATA` указывает, следует ли заполнять новую таблицу строками данных из запроса `<select>`. По умолчанию используется опция `WITH NO DATA`. Загрузка данных происходит на самом заключительном этапе фиксации транзакции, после завершения всей работы, связанной с метаданными.

Для `GLOBAL TEMPORARY TABLE ... ON COMMIT DELETE ROWS` данные не загружаются, несмотря на опцию `WITH DATA`. Запрос `<select>` не выполняется, если данные не должны быть загружены.

.Создание копии таблицы employee и заполнение её данными
[example]
====
[source,sql]
----
CREATE TABLE emp2 AS (SELECT * FROM employee) WITH DATA;
----
====

== Материализованные представления

[NOTE]
====
В настоящее время ветка с функциональностью материализованных представлений находится на финальной стадии разработки и тестирования. Эта функция будет включена в состав HQbird для Firebird 5.0 в одном из следующих обновлений.
====

*Материализованное представление* (Materialized view или MV) обладает свойствами как постоянной таблицы, так и представления. Оно определяется аналогично представлению, и его исходный запрос используется в качестве механизма для заполнения базовой таблицы MV строками данных. Изменение данных материализованного представления с помощью операторов DML запрещено. Единственный способ обновить содержимое MV — выполнить новый оператор `REFRESH` (см. ниже). Как и обычная таблица, MV может иметь индексы любого типа. В отличие от таблиц, создание ограничений и триггеров для MV запрещено.

=== Создание, модификация и удаление MV

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE [OR ALTER] MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  [WITH [NO] DATA]

ALTER MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  [WITH [NO] DATA]
----

Данные операторы создают новое или изменяют существующее материализованное представление (MV) с использованием указанного запроса и необязательного списка имен столбцов. Необязательный опция `WITH DATA` указывает, что MV должно быть заполнено данными сразу после создания (изменения). Если указана опция `WITH NO DATA` или она опущена, то MV не заполняется данными и остается пустым. Оператор `ALTER MATERIALIZED VIEW` также удаляет все существующие индексы MV. Если существует обычное (т.е. не материализованное) представление с тем же именем, генерируется ошибка.

[listing,subs="+quotes,attributes"]
----
RECREATE MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  [WITH [NO] DATA]
----

Оператор `RECREATE MATERIALIZED VIEW` удаляет *материализованное* или *обычное* представление, если оно существует, и создает новое *материализованное* представление.

Специальной команды для удаления материализованного представления нет, используйте для этого обычную инструкцию `DROP VIEW`.

=== Специальные операторы

[listing,subs="+quotes,attributes"]
----
ALTER MATERIALIZED VIEW <view_name> [(columns_names)]
  AS <query>
  TO NOT MATERIALIZED
----

Особый тип оператора `ALTER`, который преобразует *материализованное* представление в *обычное* представление с тем же именем. Зависимые объекты не затрагиваются. Все существующие индексы и строки данных прежнего материализованного представления удаляются.

[listing,subs="+quotes,attributes"]
----
ALTER  VIEW <view_name> [(columns_names)]
  AS <query>
  TO MATERIALIZED
----

Особый тип оператора `ALTER`, который преобразует *обычное* представление в *материализованное* представление с тем же именем. Зависимые объекты не затрагиваются.

=== Обновление данных материализованного представления

Для обновление данных материализованного представления используется следующий оператор.

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name> [CONCURRENTLY | DROP DATA] [CASCADE]
----

Данный оператор выполняет запрос материализованного представления (MV) и заменяет данные MV результирующим набором данных запроса. Все индексы MV обновляются соответствующим образом. Это команда DDL, и фактическое выполнение откладывается до момента `COMMIT` текущей транзакции. Существует несколько вариантов этой команды:

==== 1. Полная перезагрузка в эксклюзивном режиме

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name>
----

Этот алгоритм деактивирует все активные индексы, удаляет все существующие данные, заполняет таблицу MV строками из запроса MV и активирует все индексы, которые были деактивированы ранее. Это самый быстрый способ обновления, если в таблицах запроса MV произошло много изменений. Обратите внимание, что этот алгоритм требует эксклюзивного резервирования таблицы MV, чтобы гарантировать, что никакое другое соединение не попытается запросить MV во время её обновления. Он также используется операторами `CREATE [OR ALTER]` и `RECREATE` для первоначальной загрузки данных.

==== 2. Обновление затрагивающее только изменённые строки в режиме совместного доступа

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name> CONCURRENTLY
----

Второй вариант не требует эксклюзивного резервирования и позволяет выполнять одновременные выполнения операторов, ссылающихся на MV, во время его обновления. В этом случае механизм создает два упорядоченных курсора для данных таблицы MV и для результирующего набора запроса MV. Затем используется алгоритм слияния для обновления измененных строк, вставки новых строк и удаления строк, которые больше не существуют. Все изменения строк MV выполняются под контролем транзакций, что обеспечивает безопасный и согласованный одновременный доступ к таблице MV. Оба курсора упорядочены на основе списка столбцов уникального индекса.

Для работы этого алгоритма необходимо создать *уникальный индекс* на MV. Кроме того, текст запроса представления, хранящийся в столбце `RDB$VIEW_SOURCE`, не должен быть равен NULL, поскольку он используется механизмом для создания внутреннего оператора слияния.

Этот вариант оператора `REFRESH` следует предпочитать первому, когда требуется одновременный доступ или когда в таблицах запроса MV с момента предыдущего обновления не произошло существенных изменений.

==== 3. Удаление всех данных (эксклюзивный режим)

[listing,subs="+quotes,attributes"]
----
REFRESH MATERIALIZED VIEW <view_name> DROP DATA
----

Это оператор удаляет данные из таблицы материализованного представления и его индексы. Он полезен, когда администратору базы данных необходимо освободить место, занимаемое данными материализованного представления и его индексами. Требуется блокировка EX, как и в первом варианте оператора `REFRESH`.

==== 4. Каскадное обновление

Используйте необязательный предложение `CASCADE` для обновления всех материализованных представлений, от которых зависит данное материализованное представление. Порядок обновления гарантирует, что каждое материализованное представление будет обработано после всех материализованных представлений, от которых оно зависит.

* Использование `CONCURRENTLY` с `CASCADE` требует, чтобы все обновляемые материализованные представления имели уникальный индекс, иначе будет выдана ошибка.
* Использование `DROP DATA` с `CASCADE` удалит данные всех затронутых материализованных представлений.
* Оператор добавляет предупреждение с именем каждого материализованного представления, которое будет обработано, в вектор состояния. Это позволяет заранее (до фиксации) узнать список и порядок затронутых материализованных представлений.

=== Поддержка в gbak

Для резервного копирования с помощью `gbak` не требуется специальная поддержка. Данные материализованного представления не записываются в файл резервной копии — так же, как и для обычных представлений.

Восстановление с помощью `gbak` обновляет все материализованные представления в самом конце процесса восстановления. Материализованные представления обновляются в правильном порядке, учитывая их зависимости друг от друга (см. каскадное обновление).

Для утилиты `gbak` добавлен новый параметр командной строки, позволяющий `gbak` не обновлять материализованные представления: `-NO_MATVIEWS`. Его можно сократить до 4 начальных букв: `-NO_M`.

Соответствующий параметр в API сервисов для действия `isc_action_svc_restore` — `isc_spb_res_no_matviews`.

Обратите внимание, что резервную копию с материализованными представлениями нельзя восстановить с помощью версии Firebird, которая не поддерживает материализованные представления. Для миграции на такую ​​версию Firebird используйте оператор `ALTER MATERIALIZED VIEW ... TO NOT MATERIALIZED` перед резервным копированием. Возможно, это будет улучшено позже.
