:sectnums!:

[appendix]
[[hqbird-appx-web-api]]
= HQbird web API

HQbird FBDataGuard позволяет автоматизировать множество задач администрирования, запускать их по расписанию или по требованию из Web консоли DataGuard.

В некоторых случаях приложениям требуется запускать административные задачи, которые уже реализованы в HQbird FBDataGuard. Для разработчиков таких приложений HQbird FBDataGuard предоставляет Web API для запуска задач, настроенных в FBDataGuard.

Запускаемые задачи могут быть уровня агента, сервера или базы данных. Для успешного запуска задачи она должна быть "разрешена" (enabled в конфигурации). Для задач уровня базы данных, необходимо знать регистрационный идентификатор базы.

Все задачи запускаются через один и тот же обработчик, URI которого имеет следующий вид:

----
<schema>://<host>:<port>/agent/runnow?<parameters>

<parameters> ::= <parameter>[&<parameter> [&<parameter> ...]]

<parameter> ::= <param_name>=<param_value>
----

Здесь 

- `<schema>` - схема (в нашем случае протокол http или https);
- `<host>` - имя хоста или IP адрес на котором запущен HQbird FBDataGuard;
- `<port>` - номер порта на котором работает служба HQbird FBDataGuard;
- `<param_name>` - имя параметра;
- `<param_value>` - значение параметра.

Для конфигурации по умолчанию этот URI принимает следующий вид:

----
http://127.0.0.1:8082/agent/runnow?<parameters>
----

Для запуска задач требуются следующий параметры:

- `src` - источник (уровень задачи);
- `job` - имя задачи;
- дополнительные параметры, зависящие от задачи, например `lvl=1`;
- опциональный параметр, которым выступает некоторое, уникальное, целое число (метка времени) - которая предотвращает кэширования результата браузерами.

Источник `src` должен иметь только полную форму вида пути к задаче, примеры:

----
/agent/servers/hqbirdsrv/jobs/check-server-log
----

или

----
/agent/servers/hqbirdsrv/databases/a8005009-c850-42ec-8def-133bd8405253/jobs/lockprint
----