= Обзор HQbird

== Что такое HQbird

HQbird — это расширенный дистрибутив Firebird для предприятий с расширенными функциями:

* Встроенная репликация "один ко многим" (2.5, 3.0, 4.0, 5.0)
+
** Репликация баз данных с 1500+ соединениями
** Асинхронная репликация с задержкой 10 секунд
** Синхронная репликация
** Не требуются триггеров или других изменения в схеме, поддержка DDL, повторная инициализация в онлайн режиме
* многопоточные backup, restore, и sweep;
* поддержка шифрования;
* пул внешних соединений (ON EXTERNAL DATASOURCE);
* кеш подготовленных операторов;
* оптимизированные конфигурации;
* автоматизация резервного копирования, включая резервные копии в облаке;
* мониторинг работоспособности базы данных;
* автоматические отчеты о производительности и транзакциях;
* расширенный мониторинг транзакций и запросов (Trace, MON$ и FBScanner);
* анализ структуры базы данных;
* набор инструментов для восстановления и графический интерфейс для разработки базы данных.

Кроме того, HQbird включает самопроверку производительности для измерения производительности Firebird на определенном оборудовании и конфигурации ОС.

HQBird состоит из двух частей: Server и Admin.
Серверная часть имеет версии для Windows и Linux, а административная часть работает только на Windows.

Существует 3 версии HQbird: Standard, Professional и Enterprise.

<<<

== Что нового в HQbird 2022

HQbird 2022 is a major new release that adds support for Firebird 4 and adds a number of significant features:

. Улучшения производительности:
* Улучшения оптимизатора для автоматического распознавания неявного INNER JOIN (преобразование LEFT JOIN d INNER JOIN если запросы эквиваленты)
* Кэширование временных BLOB для ускорения операций над BLOB до 15 % и предотвращения ненормального роста размера базы данных.
* Функция `blob_append` для быстрой конкатенации BLOB, операции с BLOB до 18 раз быстрее
* Многопоточное восстановление базы данных в Firebird 4 HQbird 2022
. Потоковая обработка изменений в базе данных (технология Firebird Streaming):
* Каждое изменение (например, INSERT, UPDATE или DELETE) для каждой таблицы может быть отправлено за пределы базы данных с помощью события COMMIT.
* Возможность отправки изменений в формате JSON через RabbitMQ и аналогичное программное обеспечение.
. Набор дополнительных UDRs:
* Распознавание текста (OCR) внутри базы данных в запросах, хранимых процедурах и триггерах с поддержкой словарей.
* UDR для работы с JSON (построение и парсинг)
* Split UDR для быстрого разбиения строки по разделителю (или разделителям)
* UDR для работы с внешними источниками данных через ODBC
. Наиболее полный мониторинг производительности, основанный на MON$ и данных трассировки, позволяет легко выявлять проблемы с производительностью, от длительных транзакций до медленных или слишком часто выполняемых запросов.

Кроме того, HQbird 2022 по-прежнему предлагает расширенные функции репликации, пул внешних подключений, пул подготовленных операторов и другие функции, необходимые при работе с большими базами данных под высокой нагрузкой.

<<<

== Матрица функций

Ниже представлена матрица функций для редакций HQbird.

[cols="3,1,1,1", frame="all"]
|===
.2+h| Features 3+h| Editions
h| Standard h| Professional h| Enterprise

|Optimized Configurations
|X
|X
|X

|Backup
|X
|X
|X

|Automatic Performance Reports
|X
|X
|X

|SQL queries tracking
|X
|X
|X

|Transaction Tracking
|X
|X
|X

|Database Structure Analysis
|X
|X
|X

|Performance Test Suite
|
|X
|X

|SQL Development & Debugging
|
|X
|X

|Recovery
|
|
|X

|High Availability and Replication
|
|
|X

|Pool of Execute On External statements
|
|
|X

|Cached prepared statements
|
|
|X

|Multi-thread backup, sweep, restore
|
|
|X

|Encryption support
|
|
|X

|Enhanced authentication and security features
|
|
|X
|===

В модулях HQbird можно выделить компоненты, отвечающие за определенные операции (такие как резервное копирование, мониторинг, восстановление базы данных).

The table below shows how features are distributed among the HQbird modules:

[cols="1,1,3", frame="all", options="header"]
|===
| Функция
| Модуль
| Описание


|**Backup** (автоматическая проверка и инкрементное резервное копирование)
|FBDataGuard
|FBDataGuard работает на стороне сервера и выполняет все виды резервного копирования.

|**Optimized Configurations**
                                (три варианта конфигурационных файлов: сбалансированный, с интенсивным чтением и с интенсивной записью)
|FBDataGuard, коллекция оптимизированных конфигураций
|Оптимизированный конфигурационный файл можно настроить на основе рекомендаций FBDataGuard.

|**Performance Test Suite** (оценка оборудования)
|Performance Test Suite
|Тест измеряет производительность оборудования

|**Monitoring SQL Queries** (MON$, TraceAPI и FBScanner)
|Performance Monitor, MON$Logger, FBScanner
|В разных сценариях используются три разных метода мониторинга.

|**Health Monitoring** (онлайн проверка, проверка работоспособности БД, анализ журналов)
|FBDataGuard
|Все выполняется на сервере. FBDataGuard отправляет уведомления по электронной почте.

|**Transaction Tracking** (динамический анализ маркеров транзакций)
|FBDataGuard, Transaction Monitor, MON$Logger
|FBDataGuard отслеживает проблемы с транзакциями, Transaction Monitor и MON$Logger показывают динамику изменений и текущий статус активных транзакций.

|**Database Structure Analysis** (размеры таблиц и индексов, фрагментация, версии, и др.)
|Database Analyst
|Database Analyst подробно анализирует структуру базы данных и показывает предупреждения и рекомендации.

|**SQL Development & Debugging**
                                (инструмент с графическим интерфейсом для разработки баз данных и запросов)
|SQL Studio
|SQL Studio — мощный инструмент для разработки и отладки объектов базы данных и запросов SQL.

|**Recovery** (восстановление базы данных, восстановление резервной копии, восстановление удалённых записей)
|FirstAID, FBDataGuard, IBBackupSurgeon, IBUndelete
|FirstAID восстанавливает базы данных при их повреждении, FBDataGuard хранит важные метаданные, повышая тем самым шансы на успешное восстановление, IBBackupSurgeon экспортирует данные из поврежденных резервных копий.
IBUndelete может отменить удаление записей.

|**High Availability**
                                (репликация)
2+|HQbird Enterprise edition включает
   инструменты репликации и высокой доступности.

|**Performance improvements (пул внешних соединений и кеш подготовленных запросов)**
2+|HQbird Enterprise включает улучшения производительности.

|**Multi-thread backup, sweep, restore**
|HQbird Enterprise
|

|**Encryption support**
|HQbird Enterprise
|

|**Enhanced authentication and security features**
|HQbird Enterprise
|
|===
