= Обзор HQbird

== Что такое HQbird

HQbird -- дистрибутив СУБД Firebird для предприятий от IBSurgeon Software (www.ibaid.com), включающий в себя дополнительные функции, преимущественно повышающие производительность для больших и высоконагруженных баз данных, а также набор инструментов для организации полного цикла обслуживания баз данных без администратор базы данных (включая инструменты для оптимизации производительности, мониторинга, локального и облачного резервного копирования, а также восстановления в случае сбоев).

HQbird ускоряет работу больших баз данных (от 50 ГБ до 2 ТБ) и позволяет компаниям управлять большими базами данных, не требуя выделенного администратора баз данных для нескольких серверов или снижая расходы на поддержку многих (сотни и тысячи) серверов Firebird.

Минимальные аппаратные требования для HQbird -- 8 ГБ ОЗУ и 4 ядра. Первая версия HQbird была выпущена в 2015 году, текущая версия -- HQbird 2024.

<<<

== Как Firebird связан с HQbird?

Проще говоря, HQbird -- это корпоративная версия СУБД Firebird с открытым исходным кодом. Следуя традиции open-source проектов, мы называем Firebird "`ванильной`" версией: точно так же существует "`ванильная`" версия PostgreSQL и коммерческие версии EnterpriseDB, PostgresPro и т. д.

HQbird не является "`другой`" базой данных с точки зрения совместимости с Firebird: нет необходимости делать резервное копирование-восстановление при переключении между HQbird и Firebird, не нужно переписывать SQL или менять клиентские приложения.

Без каких-либо проблем вы можете установить HQbird и ванильную версию Firebird параллельно на одном сервере, работать с файлом базы данных с помощью HQbird, затем переключиться на ванильный Firebird, и наоборот.

100% совместимость HQbird с ванильным Firebird -- самая важная особенность HQbird!

Практически все функции, разработанные для HQbird, попадают в Firebird в пределах 1-2 версий: например, репликация появилась в HQbird версии 2.5, а в ванильном Firebird -- в версии 4.0, пул внешних соединений был разработан в HQbird 3.0 и появился в Firebird 4.0, возможности многопоточного резервного копирования, восстановления и sweep появились начиная с HQbird 2.5, и стали доступны в ванильном Firebird 5.0 и т. д.

Помимо нового функционала, ошибки, исправленные в HQbird, также исправлены в соответствующих версиях ванильного Firebird.

Также компания IBSurgeon Software проводит публичное тестирование Firebird и HQbird на предмет надежности и производительности: результаты тестирования публикуются на сайте https://www.firebirdtest.com[www.firebirdtest.com].

== Какова цена HQbird?

Постоянная лицензия на 1 сервер стоит 899 долларов США. В комплект также входит 1 лицензия на сервер реплик.

Какова будет цена HQbird для компании, которой необходимо использовать не 1 или 2 сервера, а несколько сотен или даже тысяч установок?
Если количество серверов превышает 20, покупка постоянных лицензий (899 долларов США/сервер) становится слишком дорогой. Вот почему мы предлагаем безлимитную подписку HQbird для компаний-разработчиков программного обеспечения.

Неограниченная подписка HQbird для компаний-разработчиков программного обеспечения стоит 1200 долларов США в месяц (или 13450 долларов США в год с авансовым платежом) за годовой контракт (обратите внимание, что региональные цены могут отличаться).

Это специальная лицензия для компаний-разработчиков программного обеспечения, которая позволяет устанавливать и использовать неограниченное количество копий HQbird вместе с бизнес-приложениями (ERP, CRM и т. д.), производимыми компанией.

Например, если у компании 40 клиентов, то подписка будет стоить 1200 долларов США в месяц, то есть примерно 30 долларов США на одного клиента в месяц. Если у компании-разработчика программного обеспечения 400 клиентов, то стоимость 1 клиента в месяц составит 3 доллара в месяц.

== Что нового в HQbird 2024

HQbird 2024 -- это новая крупная версия, в которой добавлена поддержка Firebird 5.0 и ряд важных функций:

* Замена запросов "на лету"
* Улучшена технология Firebird Streaming:
** Добавлен контрольный файл, с тем же форматом, который используется для репликации в Firebird 4 и выше
** Добавлено восстановление службы `fb_streaming` после сбоя (сегменты репликации не удаляются до тех пор пока транзакции начатые в них не будут завершены или откачены. После сбоя происходит повтор транзакций, которые не успели зафиксироваться).
** Добавлен новый плагин Kafka CDC (Change Data Capture)

Кроме того, HQbird 2024 по-прежнему предлагает расширенные функции репликации, пул внешних подключений, пул подготовленных операторов и другие функции, необходимые при работе с большими базами данных под высокой нагрузкой.

<<<

== Матрица функций

Ниже представлена матрица функций и уровень их поддержки в различных версиях Firebird, поставляемых в составе HQBird.

[cols="1,4,1,1,1,1,2", frame="all", options="header"]
|===
| №
| Функция
| V5.0
| V4.0
| V3.0
| V2.5
| Уровень

|1
|Высокопроизводительная встроенная репликация
|X
|X
|X
|X
|Сервер

|2
|Замена запросов "на лету"
|X
|X
|X
|X
|Сервер

|3
|Плагины для доступа к ODBC/MySQL через оператор `EXECUTE STATEMENT ON EXTERNAL`
|X
|X
|X
|
|Плагин

|4
|Кэширование BLOB во временном пространстве
|X
|X
|X
|X
|Сервер

|5
|Улучшения в оптимизаторе для JOIN и больших сортировок
|X
|X
|X
|
|Сервер

|6
|Кеш подготовленных запросов
|X
|X
|X
|
|Сервер

|7
|Firebird Streaming (плагины Kafka CDC, RabbitMQ и др.)
|X
|X
|
|
|Плагин

|8
|Полнотекстовый поиск
|X
|X
|X
|
|Плагин

|9
|Многопоточный backup/restore/sweep, создание индексов
|X
|X
|X
|X
|Сервер

|10
|Параллельное чтение согласованных данных
|X
|X
|X
|X
|Сервер

|11
|Пул внешних соединений
|X
|X
|X
|
|Сервер

|12
|Шифрование
|X
|X
|X
|
|Плагин

|13
|Автоматическая коррекция `firebird.conf` (`DefaultDbCachePages`)
|X
|X
|X
|X
|Сервер

|14
|Расширенный мониторинг производительности (трассировка, MON, блокировки, ЦП, ОЗУ, диск)
|X
|X
|X
|X
|Инструмент

|15
|Мониторинг запросов с большими сортировками
|X
|X
|X
|X
|Сервер

|16
|Управление и настройка репликации для множества баз данных с помощью инструментов командной строки.
|X
|X
|X
|X
|Инструмент

|17
|Автоматизация backup,restore и backup/restore
|X
|X
|X
|X
|Инструмент

|18
|Передача резервных копий, сегментов репликации через FTP в облако
|X
|X
|X
|X
|Инструмент

|19
|Расширенное обслуживание базы данных: правильная сборка мусора и многое другое.
|X
|X
|X
|X
|Инструмент

|20
|Поддержка множества экземпляров Firebird
|X
|X
|X
|X
|Инструмент

|21
|Тихая установка в Window и Linux
|X
|X
|X
|X
|Инструмент

|22
|Инструменты для анализа статистики
|X
|X
|X
|X
|Инструмент

|23
|Инструмент для анализа соединений/транзакций/потребления памяти/операций ввода-вывода
|X
|X
|X
|X
|Инструмент

|24
|Инструменты починки БД
|X
|X
|X
|X
|Инструмент

|25
|Оптимизированные конфигурации
|X
|X
|X
|X
|Инструмент

|===

<<<

== Краткое описание функций HQBird

=== Высокопроизводительная встроенная репликация

HQbird включает встроенную репликацию для создания отказоустойчивых систем на базе баз данных Firebird:

* Репликация баз данных с более чем 1500 подключениями.
* Асинхронная репликация с задержкой 1-30 секунд,
* Синхронная репликация без задержек,
* Никаких триггеров или других изменений в схеме не требуется.
* Автоматическое распространение изменений DDL,
* Онлайн-реинициализация реплик.
* Встроенные инструменты для передачи изменений репликации, проверка переданных сегментов репликации.

Нативная репликация настраивается через специальный плагин, с возможностью исключения записей без PK/UK на уровне плагина.

HQbird имеет полный инструментарий для организации передачи сегментов для асинхронной репликации для схем "`1-к-1`" или "`1-ко-многим`", с автоматической настройкой, передачей и проверкой сегментов репликации через сокеты или FTP. В HQbird есть инструменты командной строки для настройки баз данных для массовой репликации, выбора баз данных в папке или во вложенных папках.

=== Замена запросов "на лету"

Если у вас есть приложение с недоступными или отсутствующими исходными кодами, то HQbird может помочь вам изменить тексты несовместимых или наиболее ресурсоемких SQL-запросов "`на лету`", а значит, помочь оптимизировать производительность или произвести миграцию приложения на новую версию Firebird. Замена легко настраивается, и реализуется парами файлов, содержащих текст исходного и заменяемого запросов.

С помощью расширенного мониторинга (см. ниже № 14) вы можете найти SQL-запросы, вызывающие проблемы, а затем настроить их замену, даже без доступа к исходному коду приложения. Замененный запрос появится в  трассировке и MON$ таблицах с новым текстом.

